/**
 * Freight receipt (ใบเสร็จรับเงิน) — Pacred PDF template.
 *
 * v3 — 2026-06-09 ภูม flag round 3: literal port of Peak Account HTML.
 * Layout follows the same structure as the on-page HTML preview in
 * app/[locale]/(admin)/admin/accounting/forwarder-invoice/[id]/page.tsx.
 *
 * Server-only: imports from `./styles` which the route registers fonts for.
 */

import { Document, Page, Text, View, Image as PdfImage } from "@react-pdf/renderer";
import { styles, peakStyles, COLORS, fmtBaht } from "./styles";
import { readThaiBaht } from "@/lib/utils/thai-number";
import {
  CONTACT,
  ADDRESSES,
  SITE_LEGAL_NAME_TH,
  TAX_ID,
  BANK,
} from "@/components/seo/site";

export type FreightReceiptLine = {
  position:     number;
  description:  string;
  qty:          number;
  unit:         string;
  /** Line amount in THB (USD line × frozen exchange rate). */
  amount_thb:   number;
};

export type FreightReceiptPayment = {
  method:      string;       // localised label, e.g. "โอนผ่านธนาคาร"
  amount_thb:  number;
  paid_at:     string;       // ISO
  bank_ref:    string | null;
};

export type FreightReceiptData = {
  /** Freight invoice number — FI{YYMMDD}-{NNNN}. Null only for an un-issued draft (not rendered). */
  invoice_no:     string | null;
  /** Document lifecycle — draws the CANCELLED watermark when 'cancelled'. */
  status:         "draft" | "issued" | "cancelled";
  /** Payment settlement axis — drives the RECEIPT vs INVOICE title + the paid stamp. */
  payment_status: "unpaid" | "partial" | "paid" | "overpaid";
  issued_at:      string | null;
  created_at:     string;

  /** Reference shipment job number — printed as a cross-ref line. */
  job_no:         string | null;

  /** Buyer (consignee) snapshot at issuance — immutable per RD Code 86. */
  buyer_name:     string;
  buyer_address:  string;
  buyer_tax_id:   string | null;
  buyer_branch:   string | null;

  /** Financial snapshot (THB). */
  subtotal_thb:   number;     // Σ line amounts (commercial value in THB)
  duty_thb:       number;     // import duty
  vat_thb:        number;     // 7% import VAT
  total_thb:      number;     // grand total = subtotal + duty + vat
  paid_thb:       number;     // Σ recorded payments
  outstanding_thb: number;    // total − paid (>= 0)

  lines:          FreightReceiptLine[];
  payments:       FreightReceiptPayment[];

  /** Peak "สแกนเพื่อเปิดด้วยเว็บไซต์" QR — PNG data URL encoding the
   *  document's web URL. Generated by the route; optional so older callers
   *  keep compiling (box falls back to the gray placeholder). */
  qr_data_url?:   string | null;
};

// ── Helpers ─────────────────────────────────────────────────────────

/** Format ISO date as "DD เดือนชื่อ พ.ศ. YYYY+543". */
function formatDateThaiBE(iso: string): string {
  const d = new Date(iso);
  const months = [
    "มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน",
    "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม",
  ];
  return `${d.getDate()} ${months[d.getMonth()]} ${d.getFullYear() + 543}`;
}

/** Format tax ID as `X-XXXX-XXXXX-XX-X` (RD standard grouping). */
function formatTaxId(id: string): string {
  const digits = id.replace(/\D/g, "").slice(0, 13);
  if (digits.length !== 13) return id;
  return `${digits[0]}-${digits.slice(1, 5)}-${digits.slice(5, 10)}-${digits.slice(10, 12)}-${digits[12]}`;
}

// ── Component ───────────────────────────────────────────────────────

export function FreightReceipt({ data }: { data: FreightReceiptData }) {
  const isCancelled = data.status === "cancelled";
  const isPaid      = data.payment_status === "paid" || data.payment_status === "overpaid";
  const issueDate   = data.issued_at ?? data.created_at;

  const latestPaymentIso = data.payments.length > 0
    ? data.payments.map((p) => p.paid_at).sort().at(-1) ?? null
    : null;

  // Two-page output: ต้นฉบับ then สำเนา — same structure, different label + tint color.
  return (
    <Document
      title={`Pacred ใบเสร็จรับเงิน ${data.invoice_no ?? "DRAFT"}`}
      author="Pacred"
      subject={`ใบเสร็จรับเงิน ${data.invoice_no ?? "draft"}`}
      creator="Pacred Web (Next.js)"
    >
      <PeakFreightReceiptPage
        data={data}
        copyLabel="ต้นฉบับ"
        issueDate={issueDate}
        latestPaymentIso={latestPaymentIso}
        isPaid={isPaid}
        isCancelled={isCancelled}
      />
      <PeakFreightReceiptPage
        data={data}
        copyLabel="สำเนา"
        issueDate={issueDate}
        latestPaymentIso={latestPaymentIso}
        isPaid={isPaid}
        isCancelled={isCancelled}
      />
    </Document>
  );
}

/**
 * One A4 page — literal port of Peak Account HTML.
 * (ต้นฉบับ): orange title #FFA30A · tint bg rgba(255,163,10,0.165) → PDF flat #FFE7C2
 * (สำเนา):   gray title #5F5D5A  · tint bg rgba(95,93,90,0.165)   → PDF flat #E5E4E3
 *
 * Structure (matches HTML preview exactly):
 *   1. headerFormatOne — logo LEFT · (label) ABOVE title RIGHT
 *   2. info row — [issuer+customer stacked LEFT, each with text+contact cols] · meta-box RIGHT
 *   3. items table (Pacred 7-col — kept verbatim)
 *   4. spacer View (flex:1) pushes summary to bottom
 *   5. summary 2-col — amountInfo LEFT · big amount box RIGHT
 *   6. payment 2-col — date+total LEFT · bank RIGHT
 *   7. remark
 *   8. certified 6 boxes — QR · ผู้ออก · ผู้อนุมัติ · ตราประทับผู้ขาย · ผู้รับลูกค้า · ตราประทับลูกค้า
 */
function PeakFreightReceiptPage({
  data,
  copyLabel,
  issueDate,
  latestPaymentIso,
  isPaid,
  isCancelled,
}: {
  data: FreightReceiptData;
  copyLabel: string;
  issueDate: string;
  latestPaymentIso: string | null;
  isPaid: boolean;
  isCancelled: boolean;
}) {
  const isOriginal  = copyLabel === "ต้นฉบับ";
  // PDF: flatten the alpha-transparent colors to solid equivalents (no rgba in react-pdf)
  const tintBg      = isOriginal ? "#FFE7C2" : "#E5E4E3";  // rgba(255,163,10,0.165) / rgba(95,93,90,0.165)
  const titleColor  = isOriginal ? "#FFA30A" : "#5F5D5A";

  const grandTotal = Number(data.total_thb);
  const preTax     = Number(data.subtotal_thb) + Number(data.duty_thb);
  // Freight receipts: WHT not applied here (buyer-driven, handled upstream).
  const showWht    = false;
  const whtAmount  = 0;
  const netPaid    = grandTotal - whtAmount;

  return (
    <Page size="A4" style={[styles.page, { paddingBottom: 60 }]}>

      {/* ── 1. headerFormatOne: Pacred wordmark LEFT · (label) ABOVE title RIGHT ── */}
      <View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 }}>
        <View>
          <Text style={[peakStyles.peakBrandWord]}>Pacred</Text>
        </View>
        <View style={{ alignItems: "flex-end" }}>
          <Text style={{ fontSize: 8, color: COLORS.muted }}>({copyLabel})</Text>
          <Text style={{ fontSize: 16, fontWeight: "bold", color: titleColor, marginTop: 2 }}>
            ใบเสร็จรับเงิน
          </Text>
        </View>
      </View>

      {/* ── 2. Info row: [issuer+customer LEFT] · meta-box RIGHT ── */}
      <View style={{ flexDirection: "row", marginBottom: 6 }}>

        {/* LEFT: issuer on top, customer below */}
        <View style={{ flex: 1, marginRight: 10 }}>

          {/* ISSUER */}
          <View style={{ marginBottom: 6 }}>
            <View style={{ flexDirection: "row" }}>
              {/* TEXT column */}
              <View style={{ flex: 1, marginRight: 6 }}>
                <View style={{ flexDirection: "row", marginBottom: 1 }}>
                  <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted, width: 30 }}>ผู้ขาย :</Text>
                  <Text style={{ fontSize: 9, fontWeight: "bold", color: COLORS.foreground, flex: 1 }}>{SITE_LEGAL_NAME_TH}</Text>
                </View>
                <View style={{ flexDirection: "row", marginBottom: 1 }}>
                  <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted, width: 30 }}>ที่อยู่ :</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground, flex: 1 }}>{ADDRESSES.office.full}</Text>
                </View>
                <View style={{ flexDirection: "row" }}>
                  <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted, width: 30 }}>เลขที่ภาษี :</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground, flex: 1 }}>{TAX_ID} (สำนักงานใหญ่)</Text>
                </View>
              </View>
              {/* CONTACT column */}
              <View style={{ width: 90 }}>
                <View style={{ flexDirection: "row", marginBottom: 2 }}>
                  <Text style={{ fontSize: 8, color: COLORS.muted, width: 10 }}>T:</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground }}>{CONTACT.phoneCompanyDisplay}</Text>
                </View>
                <View style={{ flexDirection: "row", marginBottom: 2 }}>
                  <Text style={{ fontSize: 8, color: COLORS.muted, width: 10 }}>E:</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground }}>{CONTACT.emailAcc}</Text>
                </View>
                <View style={{ flexDirection: "row" }}>
                  <Text style={{ fontSize: 8, color: COLORS.muted, width: 10 }}>W:</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground }}>pacred.co.th</Text>
                </View>
              </View>
            </View>
          </View>

          {/* CUSTOMER */}
          <View>
            <View style={{ flexDirection: "row" }}>
              {/* TEXT column */}
              <View style={{ flex: 1, marginRight: 6 }}>
                <View style={{ flexDirection: "row", marginBottom: 1 }}>
                  <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted, width: 30 }}>ลูกค้า :</Text>
                  <Text style={{ fontSize: 9, fontWeight: "bold", color: COLORS.foreground, flex: 1 }}>{data.buyer_name}</Text>
                </View>
                <View style={{ flexDirection: "row", marginBottom: 1 }}>
                  <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted, width: 30 }}>ที่อยู่ :</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground, flex: 1 }}>{data.buyer_address || "-"}</Text>
                </View>
                <View style={{ flexDirection: "row", marginBottom: 1 }}>
                  <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted, width: 30 }}>เลขที่ภาษี :</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground, flex: 1 }}>
                    {data.buyer_tax_id ? formatTaxId(data.buyer_tax_id) : "-"}
                  </Text>
                </View>
                <View style={{ flexDirection: "row" }}>
                  <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted, width: 30 }}>เรียน :</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground, flex: 1 }}>-</Text>
                </View>
              </View>
              {/* CONTACT column (customer — blank) */}
              <View style={{ width: 90 }}>
                <View style={{ flexDirection: "row", marginBottom: 2 }}>
                  <Text style={{ fontSize: 8, color: COLORS.muted, width: 10 }}>T:</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground }}>-</Text>
                </View>
                <View style={{ flexDirection: "row", marginBottom: 2 }}>
                  <Text style={{ fontSize: 8, color: COLORS.muted, width: 10 }}>E:</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground }}>-</Text>
                </View>
                <View style={{ flexDirection: "row" }}>
                  <Text style={{ fontSize: 8, color: COLORS.muted, width: 10 }}>W:</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground }}>-</Text>
                </View>
              </View>
            </View>
          </View>

        </View>{/* end LEFT */}

        {/* RIGHT: meta-box */}
        <View style={{ width: 130 }}>
          <View style={{ backgroundColor: tintBg, borderRadius: 2 }}>
            <View style={{ flexDirection: "row", justifyContent: "space-between", padding: 4, marginBottom: 1 }}>
              <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted }}>เลขที่เอกสาร :</Text>
              <Text style={{ fontSize: 8, color: COLORS.foreground }}>{data.invoice_no ?? "(รอออก)"}</Text>
            </View>
            <View style={{ flexDirection: "row", justifyContent: "space-between", padding: 4, marginBottom: 1 }}>
              <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted }}>วันที่ออก :</Text>
              <Text style={{ fontSize: 8, color: COLORS.foreground }}>{formatDateThaiBE(issueDate)}</Text>
            </View>
            <View style={{ flexDirection: "row", justifyContent: "space-between", padding: 4 }}>
              <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted }}>อ้างอิง :</Text>
              <Text style={{ fontSize: 8, color: COLORS.foreground }}>{data.job_no ?? "—"}</Text>
            </View>
          </View>
        </View>

      </View>{/* end info row */}

      {/* ── 3. Items table — Pacred freight lines (description/qty/unit/amount) ── */}
      <View style={[peakStyles.peakTable, { backgroundColor: tintBg }]}>
        <View style={[peakStyles.peakTableHead, { backgroundColor: tintBg }]}>
          <Text style={[peakStyles.peakTableHeadCell, { flex: 0.6, textAlign: "center" }]}>ลำดับ</Text>
          <Text style={[peakStyles.peakTableHeadCell, { flex: 5 }]}>รายละเอียด</Text>
          <Text style={[peakStyles.peakTableHeadCell, { flex: 0.9, textAlign: "right" }]}>จำนวน</Text>
          <Text style={[peakStyles.peakTableHeadCell, { flex: 0.9, textAlign: "center" }]}>หน่วย</Text>
          <Text style={[peakStyles.peakTableHeadCell, { flex: 1.4, textAlign: "right" }]}>จำนวนเงิน (บาท)</Text>
        </View>
        {data.lines.length === 0 ? (
          <View style={[peakStyles.peakTableRow, peakStyles.peakTableRowLast, { backgroundColor: "#fff" }]}>
            <Text style={[peakStyles.peakTableCell, { flex: 9, textAlign: "center", color: COLORS.muted }]}>
              ไม่มีรายการ
            </Text>
          </View>
        ) : (
          data.lines.map((it, i) => (
            <View
              key={`${it.position}-${i}`}
              style={[
                peakStyles.peakTableRow,
                { backgroundColor: "#fff" },
                i === data.lines.length - 1 ? peakStyles.peakTableRowLast : {},
              ]}
            >
              <Text style={[peakStyles.peakTableCell, { flex: 0.6, textAlign: "center" }]}>{it.position}</Text>
              <Text style={[peakStyles.peakTableCell, { flex: 5 }]}>{it.description}</Text>
              <Text style={[peakStyles.peakTableCell, peakStyles.peakTableCellRight, { flex: 0.9 }]}>
                {Number(it.qty).toLocaleString("en-US")}
              </Text>
              <Text style={[peakStyles.peakTableCell, { flex: 0.9, textAlign: "center" }]}>{it.unit}</Text>
              <Text style={[peakStyles.peakTableCell, peakStyles.peakTableCellRight, { flex: 1.4 }]}>
                {fmtBaht(Number(it.amount_thb))}
              </Text>
            </View>
          ))
        )}
      </View>

      {/* ── 4. Spacer — pushes summary to the bottom of the page ── */}
      <View style={{ flex: 1 }} />

      {/* ── 5. Summary — 2 columns: words LEFT · big amount box RIGHT ── */}
      <View style={{ flexDirection: "row", marginBottom: 6 }}>
        {/* LEFT: สรุป + Thai words */}
        <View style={{ flex: 1, marginRight: 8 }}>
          <View style={{ flexDirection: "row" }}>
            <Text style={{ fontSize: 10, fontWeight: "bold", color: COLORS.foreground, width: 28 }}>สรุป</Text>
            <View style={{ flex: 1 }}>
              <View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 2 }}>
                <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted }}>มูลค่าไม่มีหรือยกเว้นภาษี</Text>
                <Text style={{ fontSize: 8, color: COLORS.foreground }}>{fmtBaht(preTax)} บาท</Text>
              </View>
              {Number(data.duty_thb) > 0 && (
                <View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 2 }}>
                  <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted }}>อากรขาเข้า</Text>
                  <Text style={{ fontSize: 8, color: COLORS.foreground }}>{fmtBaht(Number(data.duty_thb))} บาท</Text>
                </View>
              )}
              <View style={{ flexDirection: "row", justifyContent: "space-between", borderTopWidth: 0.5, borderTopColor: COLORS.border, paddingTop: 2 }}>
                <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted }}>จำนวนเงินทั้งสิ้น</Text>
                <Text style={{ fontSize: 8, color: COLORS.foreground, flex: 1, textAlign: "right" }}>
                  {readThaiBaht(grandTotal)}บาทถ้วน
                </Text>
              </View>
            </View>
          </View>
        </View>
        {/* RIGHT: big amount box */}
        <View style={{ width: 130 }}>
          <View style={{ backgroundColor: tintBg, borderRadius: 2, padding: 6, alignItems: "center", marginBottom: 3 }}>
            <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted }}>จำนวนเงินทั้งสิ้น</Text>
            <Text style={{ fontSize: 14, fontWeight: "bold", color: COLORS.foreground, marginTop: 2 }}>
              {fmtBaht(grandTotal)} บาท
            </Text>
          </View>
          <View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 1 }}>
            <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted }}>จำนวนเงินที่ถูกหัก ณ ที่จ่าย</Text>
            <Text style={{ fontSize: 8, color: COLORS.foreground }}>{fmtBaht(showWht ? whtAmount : 0)} บาท</Text>
          </View>
          <View style={{ flexDirection: "row", justifyContent: "space-between" }}>
            <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted }}>จำนวนเงินที่ชำระ</Text>
            <Text style={{ fontSize: 8, color: COLORS.foreground }}>{fmtBaht(netPaid)} บาท</Text>
          </View>
        </View>
      </View>

      {/* ── 6. Payment — ชำระเงิน heading + 2-col content ── */}
      <View style={{ flexDirection: "row", marginBottom: 6 }}>
        <Text style={{ fontSize: 10, fontWeight: "bold", color: COLORS.foreground, width: 28 }}>ชำระเงิน</Text>
        <View style={{ flex: 1, flexDirection: "row" }}>
          {/* LEFT: date + total */}
          <View style={{ flex: 1, marginRight: 8 }}>
            <View style={{ flexDirection: "row", marginBottom: 2 }}>
              <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted, width: 50 }}>วันที่ชำระ :</Text>
              <Text style={{ fontSize: 8, color: COLORS.foreground }}>
                {latestPaymentIso ? formatDateThaiBE(latestPaymentIso) : issueDate ? formatDateThaiBE(issueDate) : "—"}
              </Text>
            </View>
            <View style={{ flexDirection: "row" }}>
              <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.muted, width: 50 }}>จำนวนเงินรวม :</Text>
              <Text style={{ fontSize: 8, color: COLORS.foreground }}>{fmtBaht(grandTotal)} บาท</Text>
            </View>
          </View>
          {/* RIGHT: bank detail + WHT row */}
          <View style={{ flex: 1 }}>
            <View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 2 }}>
              <View>
                <Text style={{ fontSize: 8, color: COLORS.foreground }}>ธ.กสิกรไทย</Text>
                <Text style={{ fontSize: 8, fontWeight: "bold", color: COLORS.foreground }}>
                  ออมทรัพย์ {BANK.accountNumber}
                </Text>
                <Text style={{ fontSize: 8, color: COLORS.muted }}>{BANK.accountName}</Text>
              </View>
              <Text style={{ fontSize: 8, color: COLORS.foreground }}>{fmtBaht(netPaid)} บาท</Text>
            </View>
            {showWht && (
              <View style={{ flexDirection: "row", justifyContent: "space-between" }}>
                <Text style={{ fontSize: 8, color: COLORS.foreground }}>ภาษีหัก ณ ที่จ่าย</Text>
                <Text style={{ fontSize: 8, color: COLORS.foreground }}>{fmtBaht(whtAmount)} บาท</Text>
              </View>
            )}
          </View>
        </View>
      </View>

      {/* ── 7. หมายเหตุ ── */}
      <View style={{ flexDirection: "row", marginBottom: 6 }}>
        <Text style={{ fontSize: 10, fontWeight: "bold", color: COLORS.foreground, width: 28 }}>หมายเหตุ</Text>
        <Text style={{ fontSize: 8, color: COLORS.foreground, flex: 1 }}>
          {data.job_no ? `อ้างอิงงานขนส่ง: ${data.job_no}` : ""}
          {"\n"}สถานะการชำระเงิน: {paymentStatusLabel(data.payment_status)}
        </Text>
      </View>

      {/* ── 8. Certified — 6 boxes (QR · ผู้ออก · ผู้อนุมัติ · ตราประทับผู้ขาย · ผู้รับลูกค้า · ตราประทับลูกค้า) ── */}
      <View style={{ flexDirection: "row" }}>
        {/* heading */}
        <View style={{ justifyContent: "flex-end", width: 28 }}>
          <Text style={{ fontSize: 10, fontWeight: "bold", color: COLORS.foreground }}>รับรอง</Text>
        </View>
        {/* Box 1: QR — real PNG when the route supplied one, gray box otherwise */}
        <View style={{ flex: 1, alignItems: "center", marginRight: 3 }}>
          <Text style={{ fontSize: 7, fontWeight: "bold", color: COLORS.foreground, marginBottom: 2 }}>สแกนเพื่อเปิดด้วยเว็บไซต์</Text>
          {data.qr_data_url ? (
            // eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image has no alt prop
            <PdfImage src={data.qr_data_url} style={{ width: 48, height: 48, marginBottom: 2 }} />
          ) : (
            <View style={[peakStyles.peakQrSmallBox, { marginBottom: 2 }]}>
              <Text style={peakStyles.peakQrSmallText}>QR</Text>
            </View>
          )}
        </View>
        {/* Box 2: ผู้ออกเอกสาร */}
        <View style={{ flex: 1, alignItems: "center", marginRight: 3 }}>
          <Text style={{ fontSize: 7, fontWeight: "bold", color: COLORS.foreground, marginBottom: 2 }}>ผู้ออกเอกสาร (ผู้ขาย)</Text>
          <View style={peakStyles.peakSigContent} />
          <View style={peakStyles.peakSigLine} />
          <Text style={peakStyles.peakSigRoleLabel}>{" "}</Text>
          <Text style={peakStyles.peakSigDateLabel}>{formatDateThaiBE(issueDate)}</Text>
        </View>
        {/* Box 3: ผู้อนุมัติเอกสาร */}
        <View style={{ flex: 1, alignItems: "center", marginRight: 3 }}>
          <Text style={{ fontSize: 7, fontWeight: "bold", color: COLORS.foreground, marginBottom: 2 }}>ผู้อนุมัติเอกสาร (ผู้ขาย)</Text>
          <View style={peakStyles.peakSigContent} />
          <View style={peakStyles.peakSigLine} />
          <Text style={peakStyles.peakSigRoleLabel}>{" "}</Text>
          <Text style={peakStyles.peakSigDateLabel}>{formatDateThaiBE(issueDate)}</Text>
        </View>
        {/* Box 4: ตราประทับ (ผู้ขาย) */}
        <View style={{ flex: 1, alignItems: "center", marginRight: 3 }}>
          <Text style={{ fontSize: 7, fontWeight: "bold", color: COLORS.foreground, marginBottom: 2 }}>ตราประทับ (ผู้ขาย)</Text>
          <View style={peakStyles.peakSigContent} />
          <View style={peakStyles.peakSigLine} />
          <Text style={peakStyles.peakSigDateLabel}>{" "}</Text>
        </View>
        {/* Box 5: ผู้รับเอกสาร (ลูกค้า) */}
        <View style={{ flex: 1, alignItems: "center", marginRight: 3 }}>
          <Text style={{ fontSize: 7, fontWeight: "bold", color: COLORS.foreground, marginBottom: 2 }}>ผู้รับเอกสาร (ลูกค้า)</Text>
          <View style={{ flex: 1, borderWidth: 0.5, borderColor: COLORS.border, width: "100%", marginBottom: 2 }} />
          <View style={peakStyles.peakSigLine} />
          <Text style={peakStyles.peakSigDateLabel}>{data.buyer_name}</Text>
        </View>
        {/* Box 6: ตราประทับ (ลูกค้า) */}
        <View style={{ flex: 1, alignItems: "center" }}>
          <Text style={{ fontSize: 7, fontWeight: "bold", color: COLORS.foreground, marginBottom: 2 }}>ตราประทับ (ลูกค้า)</Text>
          <View style={{ flex: 1, borderWidth: 0.5, borderColor: COLORS.border, width: "100%", marginBottom: 2 }} />
          <View style={peakStyles.peakSigLine} />
          <Text style={peakStyles.peakSigDateLabel}>{" "}</Text>
        </View>
      </View>

      {/* "ได้รับเงินแล้ว" watermark when fully paid */}
      {isPaid && !isCancelled && (
        <View style={styles.cancelledOverlay} fixed>
          <Text style={[styles.cancelledText, { color: COLORS.muted }]}>
            ได้รับเงินแล้ว{latestPaymentIso ? `\n${formatDateThaiBE(latestPaymentIso)}` : ""}
          </Text>
        </View>
      )}
      {isCancelled && (
        <View style={styles.cancelledOverlay} fixed>
          <Text style={styles.cancelledText}>ยกเลิก / CANCELLED</Text>
        </View>
      )}

      {/* Footer */}
      <View style={styles.footer} fixed>
        <Text style={styles.footerText}>
          เอกสารนี้ออกโดย Pacred — สอบถาม {CONTACT.emailAcc} · {CONTACT.phoneCompanyDisplay}
        </Text>
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) => `หน้า ${pageNumber} / ${totalPages}`}
        />
      </View>
    </Page>
  );
}

/** Thai label for the payment settlement status (PDF-local — keeps the
 *  component self-contained; the validators file has the canonical map
 *  but importing it here would pull a client-bound module into the PDF). */
function paymentStatusLabel(s: FreightReceiptData["payment_status"]): string {
  switch (s) {
    case "unpaid":   return "ยังไม่ชำระ";
    case "partial":  return "ชำระบางส่วน";
    case "paid":     return "ชำระครบแล้ว";
    case "overpaid": return "ชำระเกิน";
    default:         return s;
  }
}
