/**
 * LINE Notify per-user push helper (G5 — legacy PCS port).
 *
 * ⚠️ LINE Notify was EOL'd by LINE Corp April 2025. This module is a
 *    TRANSITION implementation: keeps the migrated PCS customers'
 *    existing "Connect LINE Notify" tokens functional during the
 *    cut-over window. Long-term replacement: LINE Messaging API per-
 *    user push via lib/notifications/index.ts (ADR-0001).
 *
 * Three public surfaces:
 *
 *   1. buildLineNotifyAuthorizeUrl(state)
 *        Build the OAuth-style authorize URL the connect-button redirects
 *        to. State token is the CSRF binding to the callback handler.
 *
 *   2. exchangeLineNotifyCode(code)
 *        Exchange the `code` returned by LINE Notify for an access token.
 *        Called by app/api/linenotify/callback/route.ts.
 *
 *   3. revokeLineNotifyToken(token)  +  pushToLineNotify(userId, message)
 *        Server-side notification sender + revoke. Respects
 *        LINE_PUSH_BYPASS for parity with the Messaging-API sender.
 *
 * Legacy PHP equivalents (kept here for grep'ability):
 *
 *   member/api/linenotify/callback/index.php       → exchangeLineNotifyCode
 *   pcs-admin/api/linenotify/revoke/index.php      → revokeLineNotifyToken
 *   run-time/line/index.php  function sendLineNotify → pushToLineNotify
 *
 * Server-only — do NOT import in "use client" components.
 */

import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { logger, redactId } from "@/lib/logger";

// ── LINE Notify constants ───────────────────────────────────────────
// Endpoint URLs are documented on the (still-live as of 2026-05-24)
// LINE Notify developer page even though the service is EOL'd. Hard-
// coded here because they're not user-tunable.
const LINE_NOTIFY_AUTHORIZE_URL = "https://notify-bot.line.me/oauth/authorize";
const LINE_NOTIFY_TOKEN_URL     = "https://notify-bot.line.me/oauth/token";
const LINE_NOTIFY_REVOKE_URL    = "https://notify-api.line.me/api/revoke";
const LINE_NOTIFY_PUSH_URL      = "https://notify-api.line.me/api/notify";

// Same env switch used by the Messaging-API sender — default is
// "bypass on" (safer) unless explicitly disabled. Matches the convention
// of lib/notifications/index.ts.
const LINE_BYPASS = process.env.LINE_PUSH_BYPASS !== "false";

// ────────────────────────────────────────────────────────────────────
// AUTHORIZE URL — used by `getLineOAuthAuthorizeUrl` server action
// ────────────────────────────────────────────────────────────────────
/**
 * Build the LINE Notify OAuth authorize URL.
 *
 * Throws when LINE_NOTIFY_CLIENT_ID is unset — UI gating must prevent
 * the connect button from appearing without credentials, but throwing
 * surfaces the misconfig instead of silently producing a broken URL.
 *
 * The `state` parameter MUST be a CSRF-binding string generated by the
 * caller (server action) and validated in the callback handler. We do
 * NOT generate state inside this helper because the action needs to
 * persist it (cookie / session-store) before issuing the redirect.
 */
export function buildLineNotifyAuthorizeUrl(state: string): string {
  const clientId    = process.env.LINE_NOTIFY_CLIENT_ID;
  const callbackUrl = process.env.LINE_NOTIFY_CALLBACK_URL;

  if (!clientId) {
    throw new Error("LINE_NOTIFY_CLIENT_ID not set — LINE Notify connect-button disabled");
  }
  if (!callbackUrl) {
    throw new Error("LINE_NOTIFY_CALLBACK_URL not set — LINE Notify connect-button disabled");
  }
  if (!state) {
    throw new Error("buildLineNotifyAuthorizeUrl requires a non-empty state for CSRF binding");
  }

  // LINE Notify uses standard OAuth 2.0 authorize params. `scope=notify`
  // is the only scope this service exposes. `response_mode=form_post`
  // is NOT supported here — the callback receives `code` + `state` on
  // the query string.
  const params = new URLSearchParams({
    response_type: "code",
    client_id:     clientId,
    redirect_uri:  callbackUrl,
    scope:         "notify",
    state,
  });

  return `${LINE_NOTIFY_AUTHORIZE_URL}?${params.toString()}`;
}

// ────────────────────────────────────────────────────────────────────
// TOKEN EXCHANGE — used by api/linenotify/callback route
// ────────────────────────────────────────────────────────────────────
export type ExchangeResult =
  | { ok: true;  accessToken: string }
  | { ok: false; error: string };

/**
 * Exchange the authorization `code` returned by LINE Notify for an
 * access token. Mirrors legacy `member/api/linenotify/callback/index.php`.
 *
 * Returns `{ ok: false, error }` on any failure — caller should redirect
 * the user back to a profile/settings page with a flash message.
 */
export async function exchangeLineNotifyCode(code: string): Promise<ExchangeResult> {
  const clientId     = process.env.LINE_NOTIFY_CLIENT_ID;
  const clientSecret = process.env.LINE_NOTIFY_CLIENT_SECRET;
  const callbackUrl  = process.env.LINE_NOTIFY_CALLBACK_URL;

  if (!clientId || !clientSecret || !callbackUrl) {
    logger.error("line-notify", "exchange called without env credentials", undefined, {
      hasClientId:    Boolean(clientId),
      hasSecret:      Boolean(clientSecret),
      hasCallbackUrl: Boolean(callbackUrl),
    });
    return { ok: false, error: "line_notify_misconfigured" };
  }

  try {
    const res = await fetch(LINE_NOTIFY_TOKEN_URL, {
      method:  "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        grant_type:    "authorization_code",
        code,
        redirect_uri:  callbackUrl,
        client_id:     clientId,
        client_secret: clientSecret,
      }).toString(),
    });

    if (!res.ok) {
      const detail = await res.text().catch(() => "<no body>");
      logger.error("line-notify", "token exchange http error", undefined, {
        status: res.status, detail: detail.slice(0, 200),
      });
      return { ok: false, error: "line_notify_exchange_failed" };
    }

    const data = (await res.json()) as { access_token?: string; status?: number; message?: string };
    if (!data.access_token) {
      logger.error("line-notify", "token exchange missing access_token", undefined, {
        status: data.status, message: data.message,
      });
      return { ok: false, error: "line_notify_no_token" };
    }

    return { ok: true, accessToken: data.access_token };
  } catch (err) {
    logger.error("line-notify", "token exchange threw", err);
    return { ok: false, error: "line_notify_exchange_threw" };
  }
}

// ────────────────────────────────────────────────────────────────────
// REVOKE — called from disconnectLineNotify server action
// ────────────────────────────────────────────────────────────────────
/**
 * Revoke a LINE Notify access token. Mirrors legacy
 * `pcs-admin/api/linenotify/revoke/index.php`. Returns boolean (best-
 * effort) — callers should clear the DB token regardless of the LINE
 * API result (a 401 from the revoke endpoint usually means the token
 * was already invalidated upstream, e.g. by the user from notify-bot.line.me).
 */
export async function revokeLineNotifyToken(token: string): Promise<boolean> {
  if (!token) return false;
  try {
    const res = await fetch(LINE_NOTIFY_REVOKE_URL, {
      method:  "POST",
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!res.ok) {
      logger.warn("line-notify", "revoke returned non-2xx", { status: res.status });
    }
    return res.ok;
  } catch (err) {
    logger.error("line-notify", "revoke threw", err);
    return false;
  }
}

// ────────────────────────────────────────────────────────────────────
// PUSH — called by future dispatcher cron (later sprint)
// ────────────────────────────────────────────────────────────────────
/**
 * Push a message to a specific user's LINE Notify connection.
 *
 * Looks up the user's token from `profiles.line_notify_token` (admin
 * client — bypasses RLS so the cron dispatcher can fan out without an
 * impersonated session). When `LINE_PUSH_BYPASS=true` (default in dev),
 * logs the redacted intent and returns true without hitting the network
 * — same pattern as `lib/notifications/index.ts` sendLinePush.
 *
 * Returns `false` when:
 *   · user has no token
 *   · LINE Notify rejects the request (token revoked, rate-limited, etc.)
 *   · network/throw — logged via `logger.error`
 *
 * Channel-specific dispatch (only push when
 *   profiles.line_notify_channels[event] !== false
 * ) is the CALLER's responsibility — this helper is unconditional. The
 * channel-aware dispatcher is the later-sprint task.
 */
/**
 * Push-result discriminator. Callers (the dispatcher cron) need to
 * tell apart "token revoked, nuke it" from "transient network blip,
 * try again next tick" — the bare boolean return the foundation
 * shipped with conflated those into one branch.
 */
export type PushToLineNotifyResult =
  | { ok: true;  status: "delivered" | "bypass" }
  | { ok: false; reason: "no_token" | "token_revoked" | "rate_limited" | "transient_http" | "throw"; httpStatus?: number };

export async function pushToLineNotify(
  userId: string,
  message: string,
): Promise<PushToLineNotifyResult> {
  if (!userId || !message) return { ok: false, reason: "no_token" };

  // Bypass short-circuit — matches lib/notifications/index.ts convention:
  // dev/staging never touches the network. Returns delivered-shaped so the
  // dispatcher's bookkeeping treats it as delivered. We deliberately do
  // NOT look up the token here — a missing token only matters in
  // production where bypass is off.
  if (LINE_BYPASS) {
    logger.info("line-notify", "bypass — would push", {
      userId: redactId(userId),
      preview: message.slice(0, 80),
    });
    return { ok: true, status: "bypass" };
  }

  const admin = createAdminClient();
  const { data: profile, error } = await admin
    .from("profiles")
    .select("line_notify_token")
    .eq("id", userId)
    .maybeSingle<{ line_notify_token: string | null }>();

  if (error) {
    logger.error("line-notify", "profile lookup failed", error, { userId: redactId(userId) });
    return { ok: false, reason: "transient_http" };
  }
  const token = profile?.line_notify_token ?? null;
  if (!token) {
    logger.info("line-notify", "no token — skip push", { userId: redactId(userId) });
    return { ok: false, reason: "no_token" };
  }

  try {
    const res = await fetch(LINE_NOTIFY_PUSH_URL, {
      method:  "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization:  `Bearer ${token}`,
      },
      body: new URLSearchParams({ message }).toString(),
    });

    if (res.ok) return { ok: true, status: "delivered" };

    // 401 = customer revoked their LINE Notify grant from the
    // notify-bot.line.me dashboard. The stored token is dead; the
    // dispatcher must clear it so the next-tick scan doesn't re-try.
    if (res.status === 401) {
      logger.warn("line-notify", "token revoked", { userId: redactId(userId) });
      return { ok: false, reason: "token_revoked", httpStatus: 401 };
    }
    // 429 = LINE rate-limited us. Row stays unstamped → next tick
    // retries. The dispatcher should leave the attempts counter alone
    // (rate-limit isn't the customer's fault).
    if (res.status === 429) {
      logger.warn("line-notify", "rate limited", { userId: redactId(userId) });
      return { ok: false, reason: "rate_limited", httpStatus: 429 };
    }
    // 5xx + everything else → transient. Dispatcher increments
    // attempts so a row that never delivers eventually gets sidelined.
    logger.warn("line-notify", "push returned non-2xx", {
      status: res.status, userId: redactId(userId),
    });
    return { ok: false, reason: "transient_http", httpStatus: res.status };
  } catch (err) {
    logger.error("line-notify", "push threw", err, { userId: redactId(userId) });
    return { ok: false, reason: "throw" };
  }
}

/**
 * Nuke the customer's LINE Notify token + clear connected_at. Called
 * by the dispatcher when LINE returns 401 (token revoked upstream)
 * OR after MAX_FAILED_ATTEMPTS of consecutive failures.
 *
 * Idempotent — clearing an already-null token is a no-op.
 */
export async function clearLineNotifyToken(profileId: string): Promise<void> {
  if (!profileId) return;
  const admin = createAdminClient();
  const { error } = await admin
    .from("profiles")
    .update({
      line_notify_token:        null,
      line_notify_connected_at: null,
    })
    .eq("id", profileId);
  if (error) {
    logger.warn("line-notify", "clear-token update failed", {
      userId: redactId(profileId), reason: error.message,
    });
  } else {
    logger.info("line-notify", "token nuked", { userId: redactId(profileId) });
  }
}
