#!/usr/bin/env python3
"""
Generate supabase/migrations/0113_align_legacy_camelcase.sql containing
ALTER TABLE RENAME COLUMN statements for every casing-only divergence
between Pacred's current schema (0081_pcs_legacy_schema.sql) and ก๊อต's
canonical admin-app spec (/tmp/pacred-admin-docs/docs/database/*.md).

Also emits a JSON map (scripts/_camelcase-map.json) used by the
codemod script (gen-camelcase-codemod.py) to rewrite Pacred queries.
"""
import json
import re
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACRED_SCHEMA_SQL = REPO_ROOT / "supabase" / "migrations" / "0081_pcs_legacy_schema.sql"
ADMIN_DOCS_DIR = Path("/tmp/pacred-admin-docs/docs/database")
if not ADMIN_DOCS_DIR.exists():
    ADMIN_DOCS_DIR = Path(os.environ.get("LOCALAPPDATA", "")) / "Temp" / "pacred-admin-docs" / "docs" / "database"
MIGRATION_OUT = REPO_ROOT / "supabase" / "migrations" / "0113_align_legacy_camelcase.sql"
MAP_OUT = REPO_ROOT / "scripts" / "_camelcase-map.json"


def parse_pacred_schema(sql_path: Path) -> dict[str, list[str]]:
    text = sql_path.read_text(encoding="utf-8")
    tables: dict[str, list[str]] = {}
    pattern = re.compile(r"CREATE TABLE public\.(\w+)\s*\((.*?)\);", re.DOTALL)
    for m in pattern.finditer(text):
        name = m.group(1)
        body = m.group(2)
        cols = []
        for line in body.split("\n"):
            line = line.strip().rstrip(",")
            if not line or line.startswith("--"):
                continue
            if line.upper().startswith(("CONSTRAINT", "PRIMARY KEY", "UNIQUE", "CHECK", "FOREIGN KEY")):
                continue
            first = line.split()[0].strip('"')
            if first:
                cols.append(first)
        if cols:
            tables[name] = cols
    return tables


def parse_admin_spec(docs_dir: Path) -> dict[str, list[str]]:
    tables: dict[str, list[str]] = {}
    for md_path in sorted(docs_dir.glob("*.md")):
        if md_path.name == "README.md":
            continue
        name = md_path.stem
        text = md_path.read_text(encoding="utf-8")
        cols = []
        in_schema = False
        seen_header = False
        for line in text.split("\n"):
            stripped = line.strip()
            if stripped.startswith("## Schema"):
                in_schema = True
                continue
            if in_schema and stripped.startswith("## "):
                break
            if in_schema and stripped.startswith("|"):
                cells = [c.strip() for c in stripped.strip("|").split("|")]
                if not cells:
                    continue
                first = cells[0]
                if first.lower() in ("column", ""):
                    seen_header = True
                    continue
                if first.startswith("---") or re.match(r"^-+$", first):
                    continue
                if not seen_header:
                    continue
                colname = first.strip("`").strip()
                if colname:
                    cols.append(colname)
        if cols:
            tables[name] = cols
    return tables


def main():
    pacred = parse_pacred_schema(PACRED_SCHEMA_SQL)
    spec = parse_admin_spec(ADMIN_DOCS_DIR)

    # Build the rename map: {table: {lowercase: camelCase}}
    rename_map: dict[str, dict[str, str]] = {}
    common = sorted(set(pacred) & set(spec))

    for t in common:
        pcols_lower = {c.lower(): c for c in pacred[t]}
        scols_lower = {c.lower(): c for c in spec[t]}
        renames = {}
        for k in set(pcols_lower) & set(scols_lower):
            p_name = pcols_lower[k]
            s_name = scols_lower[k]
            if p_name != s_name:
                renames[p_name] = s_name
        if renames:
            rename_map[t] = renames

    # Save JSON map for the codemod
    MAP_OUT.parent.mkdir(parents=True, exist_ok=True)
    with MAP_OUT.open("w", encoding="utf-8") as f:
        json.dump(rename_map, f, indent=2, ensure_ascii=False, sort_keys=True)
    print(f"Wrote rename map → {MAP_OUT.relative_to(REPO_ROOT)}")

    # Build migration SQL
    total_renames = sum(len(v) for v in rename_map.values())
    table_count = len(rename_map)

    lines = []
    lines.append("-- ════════════════════════════════════════════════════════════")
    lines.append("-- 0113 · Align Pacred legacy tables → ก๊อต's camelCase spec")
    lines.append("-- ════════════════════════════════════════════════════════════")
    lines.append("-- Generated by scripts/gen-camelcase-migration.py from")
    lines.append("-- https://github.com/pacred-co/pacred-admin-next/tree/main/docs/database")
    lines.append("--")
    lines.append("-- Phase A migration (0081) lowercased every identifier when pgloader")
    lines.append("-- ported pcsc_main.sql → PostgreSQL. ก๊อต's pacred-admin-next app")
    lines.append("-- (the parallel admin rewrite) expects the original MySQL camelCase")
    lines.append("-- (`userID`, `fStatus`, `cntID`, etc.) — JS clients quote identifiers")
    lines.append("-- so unquoted folding doesn't help, the actual column names have to")
    lines.append("-- match. This migration RENAMEs every casing-divergent column to the")
    lines.append("-- camelCase form ก๊อต's docs describe.")
    lines.append("--")
    lines.append(f"-- Scope: {total_renames} RENAME COLUMN statements across {table_count} tables.")
    lines.append("-- No type changes. No data changes. Indexes + FKs auto-update via PG.")
    lines.append("--")
    lines.append("-- ⚠️ COORDINATED DEPLOY: Pacred codebase has ~2.8K Supabase-client")
    lines.append("-- column refs using lowercase strings (`.select(\"userid\")`, etc.).")
    lines.append("-- A companion codemod (scripts/gen-camelcase-codemod.py) rewrites")
    lines.append("-- those to camelCase. Apply this migration + push the rewritten")
    lines.append("-- code together — applying the migration alone breaks every Pacred")
    lines.append("-- query against `tb_*` tables until Vercel rebuilds.")
    lines.append("--")
    lines.append("-- Idempotent via IF EXISTS / IF NOT EXISTS check on the old column.")
    lines.append("-- ════════════════════════════════════════════════════════════")
    lines.append("")

    for t in sorted(rename_map.keys()):
        lines.append(f"-- ── {t} ({len(rename_map[t])} renames) ──")
        for old, new in sorted(rename_map[t].items()):
            # Idempotent: only rename if old column still exists + new doesn't
            lines.append(
                f"DO $$ BEGIN "
                f"IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='{t}' AND column_name='{old}') "
                f"AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='{t}' AND column_name='{new}') "
                f"THEN EXECUTE 'ALTER TABLE public.{t} RENAME COLUMN {old} TO \"{new}\"'; "
                f"END IF; END $$;"
            )
        lines.append("")

    MIGRATION_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote migration → {MIGRATION_OUT.relative_to(REPO_ROOT)}")
    print(f"  {total_renames} renames across {table_count} tables")


if __name__ == "__main__":
    main()
