"use server";

/**
 * Auth server actions — sign in / sign out / register (personal + juristic 3-step).
 *
 * All mutations enforce input validation (Zod) and use service-role admin client
 * only when bypassing RLS is required (creating users, OTP lookups).
 */

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { detectIdentifier, normalizePhone } from "@/lib/utils/phone";
import {
  juristicStep2Schema,
  registerJuristicStep1Schema,
  registerPersonalSchema,
  signInSchema,
  type JuristicStep2Input,
  type RegisterJuristicStep1Input,
  type RegisterPersonalInput,
  type SignInInput,
} from "@/lib/validators/auth";
import { verifyOtp } from "./otp";

type ActionResult<T = void> =
  | { ok: true; data?: T }
  | { ok: false; error: string };

// ─────────────────────────────────────────────────────────────
// Sign In
// ─────────────────────────────────────────────────────────────
export async function signIn(input: SignInInput): Promise<ActionResult<{ isAdmin: boolean }>> {
  const parsed = signInSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "invalid_input" };
  }

  const { identifier, password } = parsed.data;
  const kind = detectIdentifier(identifier);
  const supabase = await createClient();

  let resolvedEmail: string | null = null;
  let resolvedPhone: string | null = null;

  if (kind === "email") {
    resolvedEmail = identifier.trim();
  } else if (kind === "memberCode") {
    // Look up phone/email by member_code via admin client (bypass RLS — pre-auth)
    const admin = createAdminClient();
    const { data: profile } = await admin
      .from("profiles")
      .select("phone, email")
      .eq("member_code", identifier.toUpperCase())
      .maybeSingle<{ phone: string | null; email: string | null }>();

    if (!profile) return { ok: false, error: "user_not_found" };

    resolvedPhone = profile.phone;
    resolvedEmail = profile.email;
  } else {
    resolvedPhone = normalizePhone(identifier);
  }

  const { error } = resolvedPhone
    ? await supabase.auth.signInWithPassword({ phone: resolvedPhone, password })
    : resolvedEmail
      ? await supabase.auth.signInWithPassword({ email: resolvedEmail, password })
      : { error: { message: "user_not_found" } as { message: string } };

  if (error) return { ok: false, error: "invalid_credentials" };

  // Check if admin to return correct redirect target
  // (queries admins table — RBAC approach replaced legacy profiles.role)
  const supabase2 = await createClient();
  const { data: { user: signedInUser } } = await supabase2.auth.getUser();
  let isAdmin = false;
  if (signedInUser) {
    const { data: adminRows } = await supabase2
      .from("admins")
      .select("role")
      .eq("profile_id", signedInUser.id)
      .eq("is_active", true)
      .limit(1);
    isAdmin = (adminRows?.length ?? 0) > 0;
  }

  return { ok: true, data: { isAdmin } };
}

// ─────────────────────────────────────────────────────────────
// Sign Out
// ─────────────────────────────────────────────────────────────
export async function signOutAction(): Promise<never> {
  const supabase = await createClient();
  await supabase.auth.signOut();
  redirect("/");
}

// ─────────────────────────────────────────────────────────────
// Register — Personal
// ─────────────────────────────────────────────────────────────
export async function registerPersonal(
  input: RegisterPersonalInput,
): Promise<ActionResult> {
  const parsed = registerPersonalSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "invalid_input" };
  }
  const data = parsed.data;
  const phone = normalizePhone(data.phone);

  // Verify OTP (bypassed if OTP_BYPASS=true)
  const otpOk = await verifyOtp(phone, data.otp, "register");
  if (!otpOk) return { ok: false, error: "invalid_otp" };

  const admin = createAdminClient();

  // Create auth user (skip provider's own SMS — we already verified ourselves)
  const { data: created, error: createErr } = await admin.auth.admin.createUser({
    phone,
    password: data.password,
    phone_confirm: true,
    email: data.email && data.email.length > 0 ? data.email : undefined,
    email_confirm: !!(data.email && data.email.length > 0),
    user_metadata: {
      first_name: data.firstName,
      last_name: data.lastName,
    },
  });
  if (createErr || !created.user) {
    return { ok: false, error: createErr?.message ?? "signup_failed" };
  }

  // Insert profile (admin bypasses RLS, member_code auto-generated by trigger)
  const { error: profileErr } = await admin.from("profiles").insert({
    id: created.user.id,
    account_type: "personal",
    first_name: data.firstName,
    last_name: data.lastName,
    phone,
    email: data.email && data.email.length > 0 ? data.email : null,
    services: data.services,
    how_know: data.howKnow ?? null,
    status: "active",
  });
  if (profileErr) return { ok: false, error: "profile_failed" };

  // Sign in to set session cookies
  const supabase = await createClient();
  const { error: signInErr } = await supabase.auth.signInWithPassword({
    phone,
    password: data.password,
  });
  if (signInErr) return { ok: false, error: "signin_failed" };

  return { ok: true };
}

// ─────────────────────────────────────────────────────────────
// Register — Juristic Step 1 (creates user + incomplete profile)
// ─────────────────────────────────────────────────────────────
export async function registerJuristicStep1(
  input: RegisterJuristicStep1Input,
): Promise<ActionResult> {
  const parsed = registerJuristicStep1Schema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "invalid_input" };
  }
  const data = parsed.data;
  const phone = normalizePhone(data.phone);

  const otpOk = await verifyOtp(phone, data.otp, "register");
  if (!otpOk) return { ok: false, error: "invalid_otp" };

  const admin = createAdminClient();

  const { data: created, error: createErr } = await admin.auth.admin.createUser({
    phone,
    password: data.password,
    phone_confirm: true,
  });
  if (createErr || !created.user) {
    return { ok: false, error: createErr?.message ?? "signup_failed" };
  }

  const { error: profileErr } = await admin.from("profiles").insert({
    id: created.user.id,
    account_type: "juristic",
    phone,
    services: data.services,
    how_know: data.howKnow ?? null,
    status: "incomplete",
  });
  if (profileErr) return { ok: false, error: "profile_failed" };

  // Sign in (session needed for step 2/3 since they use server client + RLS)
  const supabase = await createClient();
  const { error: signInErr } = await supabase.auth.signInWithPassword({
    phone,
    password: data.password,
  });
  if (signInErr) return { ok: false, error: "signin_failed" };

  return { ok: true };
}

// ─────────────────────────────────────────────────────────────
// Register — Juristic Step 2 (update company info)
// ─────────────────────────────────────────────────────────────
export async function saveJuristicStep2(
  input: JuristicStep2Input,
): Promise<ActionResult> {
  const parsed = juristicStep2Schema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "invalid_input" };
  }
  const data = parsed.data;

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "not_signed_in" };

  const { error } = await supabase
    .from("profiles")
    .update({
      tax_id: data.taxId,
      company_name: data.companyName,
      address: {
        line: data.addressLine,
        subdistrict: data.subdistrict ?? null,
        district: data.district ?? null,
        province: data.province ?? null,
        postcode: data.postcode || null,
      },
    })
    .eq("id", user.id);

  if (error) return { ok: false, error: "update_failed" };
  return { ok: true };
}

// ─────────────────────────────────────────────────────────────
// Register — Juristic Step 3 (upload doc + insert document row)
// ─────────────────────────────────────────────────────────────
const ALLOWED_DOC_TYPES = [
  "company_affidavit",
  "vat",
  "national_id",
] as const;
type DocType = (typeof ALLOWED_DOC_TYPES)[number];

const MAX_SIZE = 10 * 1024 * 1024; // 10 MB
const ALLOWED_MIME = ["application/pdf", "image/jpeg", "image/png"];

export async function uploadJuristicDoc(
  formData: FormData,
): Promise<ActionResult<{ storage_path: string }>> {
  const file = formData.get("file");
  const docType = formData.get("docType") as DocType | null;

  if (!file || !(file instanceof File)) {
    return { ok: false, error: "no_file" };
  }
  if (!docType || !ALLOWED_DOC_TYPES.includes(docType)) {
    return { ok: false, error: "invalid_doc_type" };
  }
  if (file.size > MAX_SIZE) return { ok: false, error: "file_too_large" };
  if (!ALLOWED_MIME.includes(file.type)) {
    return { ok: false, error: "invalid_mime" };
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "not_signed_in" };

  const ext = file.name.split(".").pop() ?? "bin";
  const path = `${user.id}/${docType}/${Date.now()}.${ext}`;
  const buffer = Buffer.from(await file.arrayBuffer());

  const { error: uploadErr } = await supabase.storage
    .from("member-docs")
    .upload(path, buffer, {
      contentType: file.type,
      upsert: true,
    });
  if (uploadErr) return { ok: false, error: "upload_failed" };

  const { error: insertErr } = await supabase.from("documents").insert({
    profile_id: user.id,
    doc_type: docType,
    storage_path: path,
    mime_type: file.type,
    size_bytes: file.size,
  });
  if (insertErr) return { ok: false, error: "doc_record_failed" };

  return { ok: true, data: { storage_path: path } };
}

export async function completeJuristicRegistration(): Promise<ActionResult> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "not_signed_in" };

  const { error } = await supabase
    .from("profiles")
    .update({ status: "active" })
    .eq("id", user.id);
  if (error) return { ok: false, error: "update_failed" };

  return { ok: true };
}

// ─────────────────────────────────────────────────────────────
// OAuth
// ─────────────────────────────────────────────────────────────
export async function signInWithOAuth(
  provider: "google" | "facebook",
): Promise<ActionResult<{ url: string }>> {
  const supabase = await createClient();
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";

  const { data, error } = await supabase.auth.signInWithOAuth({
    provider,
    options: {
      redirectTo: `${siteUrl}/auth/callback`,
    },
  });

  if (error || !data.url) return { ok: false, error: error?.message ?? "oauth_failed" };
  return { ok: true, data: { url: data.url } };
}
