-- 0090_drop_spine_tables.sql — DEFERRED (do NOT apply to prod yet)
--
-- D1 Option A — drop the pre-D1 "spine" tables (cargo_containers /
-- cargo_shipments / cargo_sacks) added by migrations 0033 + 0068.
--
-- ────────────────────────────────────────────────────────────────────
-- ⚠️  WAVE 3 PREREQUISITE — DO NOT APPLY THIS MIGRATION YET ⚠️
-- ────────────────────────────────────────────────────────────────────
--
-- During Wave 2D cleanup (2026-05-20 ค่ำ) ภูม discovered that ~20 files
-- across the repo still reference cargo_containers / cargo_shipments /
-- cargo_sacks:
--   actions/admin/{containers,disbursements,qa-inspections,warehouse}.ts
--   actions/{forwarder,shipments}.ts
--   app/[locale]/(admin)/admin/{kpi,reports/*,driver-runs,search,
--     accounting/disbursements,warehouse/bulletin,
--     warehouse/qa-inspections/*,reports/containers-awaiting-th}/...
--   app/[locale]/(admin)/admin/forwarders/[fNo]/page.tsx
--   app/[locale]/(admin)/admin/service-orders/[hNo]/page.tsx
--   app/[locale]/(protected)/{service-import/[fNo],shipments/[code]}/page.tsx
--   lib/cost/container-margin.ts
--   lib/integrations/momo-jmf/types.ts (cargo-type imports)
--
-- Dropping the tables now would cause runtime errors on every page that
-- queries them. ภูม-verified empty in prod, so the queries currently
-- return [] (silent). Applying this migration as-is = sudden 500s.
--
-- Wave 3 must do the downstream cleanup FIRST:
--   1. Rewrite each cargo_containers/shipments/sacks consumer to read
--      from tb_forwarder (the legacy single source of truth).
--   2. Delete obsolete helpers in lib/warehouse/{containers,shipments,
--      sacks,bulletin,cargo-type,code-gen,lifecycle,tracking}.ts.
--   3. Delete obsolete .test.ts files for those helpers.
--   4. Verify pnpm tsc + lint + smoke + functional tests pass.
--   5. Then apply this migration.
--
-- See docs/runbook/faithful-port-plan.md "Wave 3 — downstream cleanup"
-- section for the per-file checklist.
--
-- ────────────────────────────────────────────────────────────────────
-- The actual DROP statements are below, commented out. Uncomment when
-- Wave 3 is complete. Do not delete this file — it's the audit trail.
-- ────────────────────────────────────────────────────────────────────

-- DROP TABLE IF EXISTS public.cargo_shipments CASCADE;
-- DROP TABLE IF EXISTS public.cargo_sacks CASCADE;
-- DROP TABLE IF EXISTS public.cargo_containers CASCADE;
-- DROP TABLE IF EXISTS public.containers CASCADE;

-- Marker SELECT so this migration is non-destructive when applied
-- (Supabase migration tooling requires a non-empty migration body).
SELECT 'migration 0090 — DEFERRED to Wave 3 · see file comments' AS status;
