-- ============================================================
-- 0113 (PILOT) - tb_users + tb_admin + tb_co camelCase rename
-- ============================================================
-- Pilot subset of the full 0113_align_legacy_camelcase.sql
-- (996 renames across 108 tables). Apply this first, verify
-- Pacred customer + admin flows still work, then ship the rest.
--
-- - tb_users (38 renames)
-- - tb_admin (38 renames)
-- - tb_co (4 renames)
-- Total: 80 renames across 3 tables.
--
-- Source: ก๊อต's spec at pacred-admin-next/docs/database/
-- No type changes. No data changes. Idempotent (IF EXISTS guard).
-- ============================================================

-- -- tb_users (38 renames) --
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='adminid') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='adminID') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN adminid TO "adminID"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='adminidsale') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='adminIDSale') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN adminidsale TO "adminIDSale"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='coid') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='coID') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN coid TO "coID"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='companycustomer') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='companyCustomer') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN companycustomer TO "companyCustomer"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='id') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='ID') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN id TO "ID"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='shopuser') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='shopUser') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN shopuser TO "shopUser"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='useractive') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userActive') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN useractive TO "userActive"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='useraddressid') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userAddressID') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN useraddressid TO "userAddressID"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userbirthday') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userBirthday') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userbirthday TO "userBirthday"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usercompany') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userCompany') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usercompany TO "userCompany"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usercomparison') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userComparison') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usercomparison TO "userComparison"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usercomparisonvalue') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userComparisonValue') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usercomparisonvalue TO "userComparisonValue"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usercredit') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userCredit') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usercredit TO "userCredit"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usercreditdate') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userCreditDate') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usercreditdate TO "userCreditDate"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usercreditvalue') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userCreditValue') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usercreditvalue TO "userCreditValue"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='useremail') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userEmail') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN useremail TO "userEmail"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userfacebook') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userFacebook') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userfacebook TO "userFacebook"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userid') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userID') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userid TO "userID"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userlastlogin') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userLastLogin') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userlastlogin TO "userLastLogin"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userlastname') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userLastName') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userlastname TO "userLastName"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userlineid') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userLineID') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userlineid TO "userLineID"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userlineidoa') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userLineIDOA') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userlineidoa TO "userLineIDOA"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userlinenotify') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userLineNotify') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userlinenotify TO "userLineNotify"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='username') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userName') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN username TO "userName"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usernote') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userNote') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usernote TO "userNote"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userpass') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userPass') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userpass TO "userPass"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userpaymethod') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userPayMethod') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userpaymethod TO "userPayMethod"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userpicture') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userPicture') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userpicture TO "userPicture"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userrecom') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userRecom') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userrecom TO "userRecom"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userrecoverdate') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userRecoverDate') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userrecoverdate TO "userRecoverDate"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userrecoverkey') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userRecoverKey') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userrecoverkey TO "userRecoverKey"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userregistered') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userRegistered') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userregistered TO "userRegistered"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userregisterwith') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userRegisterWith') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userregisterwith TO "userRegisterWith"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usersex') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userSex') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usersex TO "userSex"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usershipby') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userShipBy') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usershipby TO "userShipBy"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userstatus') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userStatus') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN userstatus TO "userStatus"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usertel') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userTel') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usertel TO "userTel"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='usertransporttype') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_users' AND column_name='userTransportType') THEN EXECUTE 'ALTER TABLE public.tb_users RENAME COLUMN usertransporttype TO "userTransportType"'; END IF; END $$;

-- -- tb_admin (38 renames) --
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminbirthday') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminBirthday') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminbirthday TO "adminBirthday"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='admindel') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminDel') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN admindel TO "adminDel"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminemail') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminEmail') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminemail TO "adminEmail"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminemailorg') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminEmailOrg') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminemailorg TO "adminEmailOrg"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminid') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminID') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminid TO "adminID"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminidcreate') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminIDCreate') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminidcreate TO "adminIDCreate"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminlastlogin') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminLastLogin') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminlastlogin TO "adminLastLogin"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminlastname') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminLastName') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminlastname TO "adminLastName"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminlinetokennotify') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminLineTokenNotify') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminlinetokennotify TO "adminLineTokenNotify"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminname') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminName') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminname TO "adminName"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminnickname') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminNickname') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminnickname TO "adminNickname"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminpass') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminPass') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminpass TO "adminPass"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminpicture') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminPicture') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminpicture TO "adminPicture"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminregistered') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminRegistered') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminregistered TO "adminRegistered"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminsex') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminSex') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminsex TO "adminSex"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminstatus') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminStatus') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminstatus TO "adminStatus"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminstatusa') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminStatusA') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminstatusa TO "adminStatusA"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminstatussale') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminStatusSale') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN adminstatussale TO "adminStatusSale"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='admintel') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminTel') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN admintel TO "adminTel"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='admintelorg') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminTelOrg') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN admintelorg TO "adminTelOrg"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='admintmp') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminTMP') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN admintmp TO "adminTMP"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='admintype') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='adminType') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN admintype TO "adminType"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='companytype') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='companyType') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN companytype TO "companyType"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='copyhouseregistrationfile') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='copyHouseRegistrationFile') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN copyhouseregistrationfile TO "copyHouseRegistrationFile"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='dateadminlinetokennotify') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='dateAdminLineTokenNotify') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN dateadminlinetokennotify TO "dateAdminLineTokenNotify"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='datecreate') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='dateCreate') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN datecreate TO "dateCreate"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='datedel') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='dateDel') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN datedel TO "dateDel"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='enddate') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='endDate') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN enddate TO "endDate"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='enddateoflogin') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='endDateOfLogin') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN enddateoflogin TO "endDateOfLogin"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='expirydate') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='expiryDate') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN expirydate TO "expiryDate"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='id') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='ID') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN id TO "ID"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='maritalstatus') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='maritalStatus') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN maritalstatus TO "maritalStatus"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='nationalidcard') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='nationalIDCard') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN nationalidcard TO "nationalIDCard"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='nationalidcardfile') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='nationalIDCardFile') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN nationalidcardfile TO "nationalIDCardFile"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='resumefile') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='resumeFile') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN resumefile TO "resumeFile"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='salarytype') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='salaryType') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN salarytype TO "salaryType"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='startdate') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='startDate') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN startdate TO "startDate"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='statusresetpass') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_admin' AND column_name='statusResetPass') THEN EXECUTE 'ALTER TABLE public.tb_admin RENAME COLUMN statusresetpass TO "statusResetPass"'; END IF; END $$;

-- -- tb_co (4 renames) --
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_co' AND column_name='coid') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_co' AND column_name='coID') THEN EXECUTE 'ALTER TABLE public.tb_co RENAME COLUMN coid TO "coID"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_co' AND column_name='coname') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_co' AND column_name='coName') THEN EXECUTE 'ALTER TABLE public.tb_co RENAME COLUMN coname TO "coName"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_co' AND column_name='costatus') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_co' AND column_name='coStatus') THEN EXECUTE 'ALTER TABLE public.tb_co RENAME COLUMN costatus TO "coStatus"'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_co' AND column_name='id') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tb_co' AND column_name='ID') THEN EXECUTE 'ALTER TABLE public.tb_co RENAME COLUMN id TO "ID"'; END IF; END $$;
