-- ════════════════════════════════════════════════════════════
-- 0199 · customer_quotations — persisted ใบเสนอราคา for a public share-link
-- ════════════════════════════════════════════════════════════
-- Owner ภูม 2026-06-22: the ใบเสนอราคา (quotation) tool
-- (app/[locale]/(admin)/admin/customers/[id]/quote-tab.tsx) was a pure-client,
-- EPHEMERAL tool — sales could only "คัดลอกเป็นข้อความ" or browser-print; nothing
-- was saved + nothing could be sent as a link. Sales wants a PUBLIC share-link
-- they copy + send to the customer, who clicks → sees the quotation preview
-- WITHOUT login — EXACTLY mirroring the existing public receipt `/r/[token]`.
--
-- This table is the persistence the receipt path never needed (a receipt already
-- has a row in tb_receipt; a quotation had no row at all). One row per
-- shared quotation snapshot. The public page re-renders the STORED `payload`
-- (no recompute) so the customer sees byte-identical numbers to the admin card.
--
-- Access model (mirrors the receipt public page exactly):
--   - WRITE: admin server-action (actions/admin/save-quotation.ts) via the
--            service-role client → bypasses RLS.
--   - PUBLIC READ: the /q/[token] page loads the row with the SAME service-role
--            client (createAdminClient), gated by the unguessable HMAC token
--            (lib/quote/quote-token.ts). NO anon RLS read policy — exactly how
--            /r/[token] + loadReceiptDocument() expose a public document.
--   So RLS is enabled with NO permissive policy: anon/auth clients see nothing;
--   only the service-role path (write + token-gated public read) reaches the row.
--
-- Isolation: NO FK to tb_* (userid is the legacy text member code, not a FK).
-- Idempotent (safe to re-run).
-- ════════════════════════════════════════════════════════════

create table if not exists public.customer_quotations (
  id                bigint generated by default as identity primary key,
  -- The customer this quote is FOR — the legacy tb_users.userID text code
  -- (e.g. "PR10899"). Plain text, NOT a FK (legacy id space).
  userid            text not null,
  -- The human document number shown on the card, e.g. "QT-PR10899-20260622".
  ref_no            text not null,
  -- EVERYTHING the QuoteCard needs to re-render byte-identically: the line/compare
  -- rows, buyer name/taxid/address/phone, computed totals (incl. juristic 1% WHT),
  -- juristic flag, mode (compare|calc), package label, conditions/notes, etc.
  -- (the serialized `QuoteModel` from quote-tab.tsx). Render-only — never recomputed.
  payload           jsonb not null,
  -- The admin (auth.users uuid) that created the shared quote.
  created_by_admin  text,
  created_at        timestamptz not null default now()
);

-- Lookups are by primary id (the token carries the id) — the PK index suffices.
-- A by-customer index helps a future "quotes for this customer" admin view.
create index if not exists customer_quotations_userid_idx
  on public.customer_quotations (userid, created_at desc);

alter table public.customer_quotations enable row level security;

-- NO permissive RLS policy on purpose. The write path + the public read path both
-- use the service-role client (which bypasses RLS); the public page is gated by the
-- HMAC capability token, not by RLS — identical to the receipt /r/[token] model.

comment on table public.customer_quotations is
  'Persisted ใบเสนอราคา snapshots for the public share-link /q/[token]. The public page re-renders the stored jsonb payload (no recompute → same numbers as the admin card). Write + token-gated public read both via service_role; RLS enabled with no permissive policy (capability-token gated, mirrors receipt /r/[token]). NO FK to legacy. Created 2026-06-22.';
comment on column public.customer_quotations.userid is 'Customer legacy member code (tb_users.userID text, e.g. PR10899). Not a FK.';
comment on column public.customer_quotations.ref_no is 'Human doc number on the card, e.g. QT-PR10899-20260622.';
comment on column public.customer_quotations.payload is 'Serialized QuoteModel — everything the QuoteCard needs to re-render byte-identically. Render-only.';
comment on column public.customer_quotations.created_by_admin is 'auth.users uuid of the admin who shared this quote.';
