-- 0201_imported_leads.sql
-- ปอน 2026-06-22: CRM lead-import workspace (Ultra Admin Z · /admin/leads
-- "มอบหมายโทรเซลล์"). Persists CSV-imported PROSPECT leads (not tb_users
-- customers) + their assigned sales rep + call-outcome state, so ultra can
-- import a list, assign reps, and the rep works/calls them.
--
-- Additive · isolated · NO FK to any tb_* · RLS service-role-only (the app
-- reaches it via createAdminClient, which bypasses RLS — same as 0200).
-- Idempotent (safe to re-run).

create table if not exists public.imported_leads (
  id                bigint generated by default as identity primary key,
  name              text        not null default '',
  address           text        not null default '',
  phone             text        not null default '',
  line_facebook     text        not null default '',
  email             text        not null default '',
  service           text        not null default '',   -- UI dropdown: FCL/CARGO/เคลียร์ศุลกากร/ฝากสั่ง/ฝากโอนชำระ (free text on import)
  source            text        not null default '',   -- Axelra / TT / Pcs / Pacred
  assigned_admin_id text        not null default '',   -- rep legacy adminID (tb_admin.adminID = tb_users.adminIDSale); '' = unassigned
  assigned_at       timestamptz,
  call_status       text        not null default '',   -- '' | closed | no_answer | called | not_interested  (mirrors LEAD_CALL_STATUSES)
  call_count        integer     not null default 0,
  last_called_at    timestamptz,
  created_by        uuid,                               -- admin profile_id who imported
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists imported_leads_assigned_idx
  on public.imported_leads (assigned_admin_id, created_at desc);
create index if not exists imported_leads_source_idx
  on public.imported_leads (source);

-- Per-call history (time / caller / outcome) — "บันทึกว่าโทรกี่โมง วันไหน กี่ครั้ง".
create table if not exists public.imported_lead_calls (
  id         bigint generated by default as identity primary key,
  lead_id    bigint      not null references public.imported_leads(id) on delete cascade,
  admin_id   text        not null default '',          -- caller legacy adminID / uuid
  status     text        not null default 'called',    -- outcome stamped at call time
  note       text        not null default '',
  called_at  timestamptz not null default now()
);

create index if not exists imported_lead_calls_lead_idx
  on public.imported_lead_calls (lead_id, called_at desc);

alter table public.imported_leads      enable row level security;
alter table public.imported_lead_calls enable row level security;
-- 0200 pattern: NO permissive policy — all access is via the service-role
-- client (createAdminClient bypasses RLS). Admin server actions gate by role.

comment on table public.imported_leads is
  'CRM CSV-imported prospect leads + assigned rep + call state (ปอน · Ultra Admin Z · created 2026-06-22).';
comment on table public.imported_lead_calls is
  'Per-call history for imported_leads (called_at / admin_id / outcome status).';
