-- 0204_cms_articles.sql
-- Owner 2026-06-23: no-code article CMS — back-office editor (Extensions →
-- "เขียนบทความ") → Ultra Admin Z approves → the article goes LIVE on the public
-- site, appended to the existing static cards. THREE categories, mapped to the
-- existing public surfaces:
--   knowledge → /knowledge   · news → /news   · our_work → /our-work
-- The body is PLAIN TEXT rendered by <ArticleContent> (the same parser the
-- legacy .txt knowledge bodies use) — no HTML/markdown needed (truly no-code).
--
-- Additive · isolated · NO FK to tb_*/profiles (author/approver = profile_id
-- soft refs). RLS service-role-only (the app reaches it via createAdminClient;
-- admin actions gate by role · public pages read published rows via a server
-- action). Idempotent (safe to re-run).

create table if not exists public.cms_articles (
  id              bigint generated by default as identity primary key,
  category        text        not null default 'knowledge', -- knowledge | news | our_work
  title           text        not null default '',
  slug            text        not null,                     -- url key for /articles/<slug>
  excerpt         text        not null default '',
  cover_url       text        not null default '',          -- public storage URL (avatars bucket · articles/)
  body            text        not null default '',          -- plain text → <ArticleContent>
  sub_category    text        not null default '',          -- knowledge badge: นำเข้า/เคลียร์/ส่งออก (else free)
  status          text        not null default 'draft',     -- draft | pending | published | rejected
  author_admin_id uuid,                                     -- profile_id of the writer
  approved_by     uuid,                                     -- profile_id of the ultra approver
  reject_note     text        not null default '',          -- ultra's reason when sent back
  published_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create unique index if not exists cms_articles_slug_key
  on public.cms_articles (slug);
create index if not exists cms_articles_cat_status_idx
  on public.cms_articles (category, status, published_at desc nulls last);
create index if not exists cms_articles_author_idx
  on public.cms_articles (author_admin_id, updated_at desc);

alter table public.cms_articles enable row level security;
-- No permissive policy (0200/0201 pattern) — all access via the service-role
-- client; admin actions gate by role, public reads go through a server action.

comment on table public.cms_articles is
  'No-code CMS articles (knowledge/news/our_work) · write → ultra approve → public. Owner 2026-06-23.';
