-- 0210_case_comments.sql
-- ปอน 2026-06-25: public case-study comments on /our-work/[id]. A signed-in
-- customer can leave a comment (login REQUIRED) — comments render in the new
-- "ความคิดเห็น" section under "ผลงานอื่นๆ". Additive · isolated · NO FK to
-- profiles (author = soft profile_id ref · name/avatar snapshotted on insert).
-- RLS enabled, NO permissive policy (0204 cms_articles pattern) — the app
-- reads/writes via the service-role client inside server actions:
--   listCaseComments → public-read the `status='visible'` rows
--   postCaseComment  → gated on a signed-in session (lib/auth/get-user)
-- `status` defaults 'visible' (auto-shown); change the default to 'pending'
-- (or hide rows) to add moderation later. Idempotent (safe to re-run).
--
-- ⚠️ NOT YET APPLIED — เดฟ to apply to prod (yzljakczhwrpbxflnmco) + DEV-sync.
-- Until applied, the comment section renders (login gate + empty state) and the
-- actions fail-soft (list → [] · post → friendly error). NEXT FREE = 0211.

create table if not exists public.case_comments (
  id                bigint generated by default as identity primary key,
  case_slug         text        not null,            -- the /our-work/<id> key (review.id)
  author_profile_id uuid,                            -- profiles.id (soft ref)
  author_name       text        not null default '', -- display-name snapshot
  author_avatar     text,                            -- avatar URL snapshot
  body              text        not null default '',
  status            text        not null default 'visible', -- visible | pending | hidden
  created_at        timestamptz not null default now()
);

create index if not exists case_comments_slug_idx
  on public.case_comments (case_slug, status, created_at desc);

alter table public.case_comments enable row level security;
-- No permissive policy — all access via the service-role client in server actions.

comment on table public.case_comments is
  'Public case-study comments on /our-work/[id] · login-gated insert · ปอน 2026-06-25.';
