/**
 * Legacy `tb_users` bridge — write a tb_users row for a freshly-signed-up
 * Pacred customer so the admin /admin/customers/pending queue can see them.
 *
 * E2E loop fix · Agent F1 · 2026-05-29 (Gap #1):
 *   Before this helper, `registerPersonal` + `registerJuristicStep1` wrote
 *   ONLY to `profiles` with status='active' / 'incomplete'. The admin
 *   pending queue (`/admin/customers/pending`) reads `tb_users WHERE
 *   userActive='0'` — so new Pacred signups never appeared in the queue
 *   and were therefore never approved/auto-assigned to a sales rep. The
 *   approve action also flips `tb_users.userActive='1'`, so without a
 *   tb_users row the approve flow had nothing to act on.
 *
 *   This bridge closes that gap: after the profile insert succeeds and
 *   the trigger has minted a `member_code` (e.g. PR12345), call
 *   `insertLegacyTbUserRow()` to mirror the customer into `tb_users` with:
 *     - userID         = member_code
 *     - userActive     = '0'    (= pending approval; admin queue picks up)
 *     - userStatus     = '1'    (= active not-deleted)
 *     - userRegistered = now()
 *     - userName/userLastName/userTel/userEmail populated from form
 *     - userCompany    = '0' (personal) or '1' (juristic)
 *
 * Transaction safety
 *   The profile insert happens first; this bridge runs after. If the
 *   tb_users insert fails the profile row stays (the customer's auth +
 *   profile still work — just no pending-queue visibility). We log loud
 *   so ops can manually `INSERT INTO tb_users` and approve. We do NOT
 *   roll back the profile because that would also have to delete the
 *   auth.user — a 3-table rollback that's much riskier than the visible
 *   ops follow-up.
 *
 * Post-0113 schema: `tb_users` columns are camelCase + quoted (per
 * migration 0113). All select/insert keys use the quoted camelCase form.
 *
 * Server-only.
 */
import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { logger, redactPhone } from "@/lib/logger";
import { pickLeastLoadedSalesRep } from "@/lib/admin/assign-sales-rep";
import { pickLeastLoadedCsRep } from "@/lib/admin/assign-cs-rep";

const SCOPE = "legacy-bridge-tb-users";

export type LegacyTbUserInput = {
  /** Generated by the profiles trigger — `PR<n>` form (e.g. `PR12345`). */
  memberCode: string;
  /** E.164 phone (already normalized by `normalizePhone()` in the action). */
  phone: string;
  /** Empty string OK — column is nullable in 0081 + later. */
  email: string | null;
  /** "personal" → userCompany='0' · "juristic" → userCompany='1'. */
  accountType: "personal" | "juristic";
  /** First name (personal) — empty string for juristic step 1 (filled in step 2). */
  firstName: string | null;
  /** Last name (personal) — empty string for juristic step 1. */
  lastName: string | null;
};

/**
 * Insert a tb_users row mirroring a freshly-created profile. Best-effort:
 * logs + returns `{ok:false}` on failure, never throws (the caller has
 * already committed the profile + auth user — losing the tb_users mirror
 * is bad but not catastrophic; ops can manually backfill).
 *
 * Idempotent on userID conflict — if a tb_users row with the same
 * member_code already exists (rare edge: rerun of /register with same
 * member_code already assigned), we no-op rather than fail.
 */
export async function insertLegacyTbUserRow(
  admin: SupabaseClient,
  input: LegacyTbUserInput,
): Promise<{ ok: boolean; error?: string }> {
  const {
    memberCode,
    phone,
    email,
    accountType,
    firstName,
    lastName,
  } = input;

  if (!memberCode) {
    logger.error(SCOPE, "missing memberCode — refusing to insert tb_users row", undefined, {});
    return { ok: false, error: "missing_member_code" };
  }

  // tb_users.usertel is varchar(13) NOT NULL and legacy stored 10-digit
  // local phone (`0948782006`). Pacred profiles store E.164 (`+66948782006`).
  // Strip the `+66` and re-prepend `0` so the legacy column gets the
  // 10-digit form the legacy ops UI expects.
  const legacyTel = e164ToLegacyThaiPhone(phone);

  // userRegistered is a `timestamp without time zone` per 0081 — use
  // ISO without timezone. Supabase REST handles the date+time string;
  // for fidelity with legacy NOW() we use UTC-now ISO.
  const nowIso = new Date().toISOString();

  // Pre-check — idempotent guard. The next attempt of /register with
  // the same identifier hits the profile-unique-constraint long before
  // here, but on the off chance a partial state landed (the only way
  // this happens is an admin manually restored a profile but its
  // tb_users row was deleted) we no-op rather than fail.
  const { data: existing, error: existingErr } = await admin
    .from("tb_users")
    .select("userID")
    .eq("userID", memberCode)
    .maybeSingle();
  if (existingErr) {
    // Not fatal — the insert below will re-surface the same error if
    // it's a real problem (RLS / column / schema). Log + continue.
    logger.warn(SCOPE, "tb_users existence pre-check failed — continuing to insert", {
      memberCode,
      reason: existingErr.message,
    });
  }
  if (existing) {
    logger.info(SCOPE, "tb_users row already exists — skipping insert (idempotent)", {
      memberCode,
    });
    return { ok: true };
  }

  // Phone-collision guard. `tb_users.userTel` carries a UNIQUE index
  // (`idx_*_usertel`) — a raw insert with a phone that already belongs to
  // another userID throws 23505 and (pre-2026-05-29) silently orphaned the
  // signup. This happens for genuine re-registrations (same person signs up
  // again with a fresh member_code) + legacy rows that share the number.
  // We pre-check and no-op: the customer already HAS a tb_users identity
  // under the other code, so the admin queue + approve flow can still act on
  // them via that row. Logged at info (expected), not error.
  //
  // Ghost-PR fix (2026-06-11): the pre-check had NO userStatus filter, so a
  // soft-deleted (userStatus='0') account that still holds the phone would
  // make this no-op {ok:true} and insert NOTHING → the fresh signup became a
  // ghost (profiles + member_code with no tb_users mirror). Align with
  // findLegacyUserIdByPhone's filter (userStatus != '0'): a soft-deleted phone
  // owner must NOT block the mirror insert. The customer is genuinely starting
  // over; the real unique index still guards against a LIVE duplicate below
  // (the 23505 branch degrades that to a no-op too).
  const { data: phoneOwner, error: phoneOwnerErr } = await admin
    .from("tb_users")
    .select("userID")
    .eq("userTel", legacyTel)
    .neq("userStatus", "0")
    .maybeSingle();
  if (phoneOwnerErr) {
    // Not fatal — same as the userID pre-check above: the insert below will
    // re-surface a real problem. Log + continue.
    logger.warn(SCOPE, "tb_users phone-collision pre-check failed — continuing to insert", {
      memberCode,
      reason: phoneOwnerErr.message,
    });
  }
  if (phoneOwner) {
    logger.info(
      SCOPE,
      "tb_users phone already registered under another member — skipping insert (no orphan)",
      { memberCode, existingUserID: phoneOwner.userID, phone: redactPhone(phone) },
    );
    return { ok: true };
  }

  // Pacred-native customers default useractive='0' (= pending admin
  // approval). The admin queue at /admin/customers/pending reads
  // `userActive='0'` to enumerate this list. Approval (Sub-fix B) flips
  // to '1' and triggers the SMS + sales-rep auto-assign.
  //
  // NOT-NULL columns per 0081 (carry sane defaults so the insert
  // doesn't trip a constraint violation):
  //   userLineNotify · userCompany · userComparison · userComparisonValue
  //   userCredit · userCreditValue · userCreditDate · shopUser · channel
  //   userRecom · userAddressID · userTransportType · userShipBy
  //   userPayMethod · userNote · userLineIDOA · companyCustomer
  //   userPicture · userPass · coID
  //
  // userPass is varchar(80) NOT NULL — supabase auth holds the real password.
  // Empty string here is intentional: legacy admin UIs read userPass only when
  // the user signs in via the legacy /member/login.php flow, which Pacred users
  // never use (they go through Supabase auth on /login). The bridge sign-in
  // (`pcs-legacy-bridge.ts`) operates the OTHER direction — legacy → Supabase.
  //
  // P1-15 (2026-05-31): assign a sales rep AT REGISTER (faithful to legacy
  // check-otp-register.php L60-95). Before this, leads were rep-less until an
  // admin approved them — breaking "ทีมเซลล์จะโทรหา" (the rep can't call a
  // lead they don't yet own). The new customer is userActive='0' so it's not
  // counted in the round-robin's own load tally.
  //
  // 2026-06-02 (legacy model): pickLeastLoadedSalesRep now reads the legacy
  // tb_admin sales pool (adminStatusA='1' AND adminStatusSale='1') and NEVER
  // returns null — when the pool is empty it returns the central rep
  // (admin_center) so the lead is always owned. The register action re-reads
  // this via getSalesRepContactForUserid(memberCode) for the success popup.
  const assignedSalesRep = await pickLeastLoadedSalesRep(admin);
  // CS round-robin (2026-06-05) — mirror the sales assignment so every new
  // customer is owned by BOTH a เซล and a CS at signup. Never empty (central
  // CS fallback = admin_ploy / พลอย).
  const assignedCsRep = await pickLeastLoadedCsRep(admin);

  const payload: Record<string, unknown> = {
    userID:               memberCode,
    userTel:              legacyTel,
    userStatus:           "1",   // 1=ใช้งาน (not deleted)
    userActive:           "0",   // 0=pending admin approval
    userPass:             "",    // not used by Pacred-native auth path
    userName:             firstName ?? "",
    userLastName:         lastName  ?? "",
    userEmail:            email ?? null,
    userRegistered:       nowIso,
    userPicture:          "user.jpg",
    coID:                 "PR",  // Pacred co-id (legacy was 'PCS')
    userLineNotify:       "",
    userCompany:          accountType === "juristic" ? "1" : "0",
    userComparison:       "0",
    userComparisonValue:  0,
    userCredit:           "0",
    userCreditValue:      0,
    userCreditDate:       0,
    shopUser:             "1",   // ซื้อไปใช้เอง default
    channel:              "",
    userRecom:            "",
    userAddressID:        "",
    userTransportType:    "",
    userShipBy:           "",
    userPayMethod:        "",
    userNote:             "",
    userLineIDOA:         "",
    companyCustomer:      "0",
    adminIDSale:          assignedSalesRep,  // P1-15: rep owned at signup (never empty)
    adminIDCS:            assignedCsRep,     // 2026-06-05: CS owned at signup (never empty)
  };

  const { error: insertErr } = await admin.from("tb_users").insert(payload);
  if (insertErr) {
    // 23505 = unique_violation. Two distinct sources, treated differently:
    //
    //  · userID (PK) collision — a row with this member_code already exists
    //    (rerun of register with the same code). Genuinely idempotent: the
    //    customer already HAS their mirror under this exact code → {ok:true}.
    //
    //  · usertel collision — the phone is taken by ANOTHER row. With the
    //    soft-deleted-aware pre-check above (`.neq userStatus '0'`), this now
    //    fires when ONLY a soft-deleted (userStatus='0') account holds the
    //    phone: the pre-check correctly let us through, but the FULL unique
    //    index on usertel (0082 · not partial) still blocks the insert. NO row
    //    landed under our member_code → blanket {ok:true} here would strand a
    //    ghost PR. Report {ok:false} so the caller's verify-and-rollback
    //    (registerPersonal) cleans up instead of leaving an unreachable orphan.
    //
    // The error details name the offending constraint (Postgres includes the
    // index/constraint name). usertel index = `idx_17047_usertel` (0082).
    if (insertErr.code === "23505") {
      const blob = `${insertErr.details ?? ""} ${insertErr.message ?? ""}`.toLowerCase();
      const isUserTelCollision = blob.includes("usertel");
      if (isUserTelCollision) {
        logger.error(SCOPE, "tb_users insert blocked by usertel unique index — phone held by another (likely soft-deleted) row · NO mirror landed", insertErr, {
          memberCode,
          phone: redactPhone(phone),
          constraint: insertErr.details ?? insertErr.message,
        });
        return { ok: false, error: "phone_collision_no_row" };
      }
      logger.info(SCOPE, "tb_users insert hit userID unique constraint — already present (no orphan)", {
        memberCode,
        constraint: insertErr.details ?? insertErr.message,
      });
      return { ok: true };
    }
    logger.error(SCOPE, "tb_users insert failed — orphan profile risk", insertErr, {
      memberCode,
      accountType,
      phone: redactPhone(phone),
      code: insertErr.code,
      message: insertErr.message,
      details: insertErr.details,
      hint:    insertErr.hint,
    });
    return { ok: false, error: insertErr.message };
  }

  logger.info(SCOPE, "tb_users row created for new signup", {
    memberCode,
    accountType,
  });

  // P1-16 (2026-05-30) — seed the customer's legacy money-plane rows so a
  // Pacred-native signup is a FULL citizen of tb_*, not a functional orphan.
  // Legacy `check-otp-register.php` L117-120 runs these two INSERTs right
  // after the tb_users INSERT succeeds (same order). Without them a new
  // customer has NO tb_wallet ledger row (migrated customers all do) — every
  // wallet read (lib/legacy/pcs-chrome.ts badge · /wallet) falls through to
  // ฿0-or-missing, and the wallet-money-loop (ADR-0018) has no row to
  // debit/credit. Best-effort (mirrors the bridge's no-throw philosophy): a
  // failure here logs loud but never rolls back the already-committed
  // tb_users + profile.
  await seedLegacyWalletRows(admin, memberCode);

  return { ok: true };
}

/**
 * Seed the two legacy money-plane rows for a brand-new customer — the faithful
 * port of `check-otp-register.php` L117-120:
 *
 *     INSERT INTO tb_wallet    (userID) VALUE ('$userID');   // wallettotal → 0.00 default
 *     INSERT INTO tb_cash_back (userID) VALUE ('$userID');   // cbtotal → 0 (see note)
 *
 * Schema (0081_pcs_legacy_schema.sql · all-lowercase, NOT in the 0113
 * camelCase batch — verified no later migration renamed these):
 *   tb_wallet    (userid varchar(10) NOT NULL, wallettotal numeric(10,2) DEFAULT 0.00)
 *   tb_cash_back (userid varchar(10) NOT NULL, cbtotal     numeric(10,2) NOT NULL)
 *
 * `cbtotal` is NOT NULL with NO column default. Legacy MySQL's non-strict mode
 * filled the omitted column with an implicit 0; Postgres has no implicit
 * default, so we set `cbtotal: 0` explicitly to (a) not trip the NOT NULL
 * constraint and (b) reproduce legacy's effective result. `tb_wallet` does
 * carry a DEFAULT 0.00, so wallettotal is left to the default for fidelity.
 *
 * Idempotent: pre-checks each row and no-ops if it already exists (rerun of
 * the register bridge, or a customer that was partially seeded before). Each
 * insert is independent — a failure on one is logged but does NOT block the
 * other (a missing cashback row must not prevent the wallet row, and vice
 * versa). Returns which rows are now present so callers/tests can assert.
 */
export async function seedLegacyWalletRows(
  admin: SupabaseClient,
  memberCode: string,
): Promise<{ wallet: boolean; cashBack: boolean }> {
  const result = { wallet: false, cashBack: false };
  if (!memberCode) {
    logger.error(SCOPE, "seedLegacyWalletRows: missing memberCode — skipping", undefined, {});
    return result;
  }

  // ── tb_wallet ──────────────────────────────────────────────────────────
  const { data: existingWallet, error: walletReadErr } = await admin
    .from("tb_wallet")
    .select("userid")
    .eq("userid", memberCode)
    .maybeSingle();
  if (walletReadErr) {
    logger.warn(SCOPE, "tb_wallet existence pre-check failed — continuing to insert", {
      memberCode,
      reason: walletReadErr.message,
    });
  }
  if (existingWallet) {
    result.wallet = true;
    logger.info(SCOPE, "tb_wallet row already exists — skipping seed (idempotent)", { memberCode });
  } else {
    // Insert userid only — wallettotal rides its DEFAULT 0.00 (legacy parity).
    const { error: walletInsErr } = await admin
      .from("tb_wallet")
      .insert({ userid: memberCode });
    if (walletInsErr) {
      if (walletInsErr.code === "23505") {
        // Lost the race to a concurrent seed — the row exists, that's fine.
        result.wallet = true;
        logger.info(SCOPE, "tb_wallet insert hit unique constraint — already seeded (no orphan)", {
          memberCode,
        });
      } else {
        logger.error(SCOPE, "tb_wallet seed failed — new customer has no wallet ledger row", walletInsErr, {
          memberCode,
          code: walletInsErr.code,
          message: walletInsErr.message,
        });
      }
    } else {
      result.wallet = true;
      logger.info(SCOPE, "tb_wallet row seeded for new signup", { memberCode });
    }
  }

  // ── tb_cash_back ───────────────────────────────────────────────────────
  const { data: existingCashBack, error: cbReadErr } = await admin
    .from("tb_cash_back")
    .select("userid")
    .eq("userid", memberCode)
    .maybeSingle();
  if (cbReadErr) {
    logger.warn(SCOPE, "tb_cash_back existence pre-check failed — continuing to insert", {
      memberCode,
      reason: cbReadErr.message,
    });
  }
  if (existingCashBack) {
    result.cashBack = true;
    logger.info(SCOPE, "tb_cash_back row already exists — skipping seed (idempotent)", { memberCode });
  } else {
    // cbtotal is NOT NULL with no default — set 0 explicitly (see docblock).
    const { error: cbInsErr } = await admin
      .from("tb_cash_back")
      .insert({ userid: memberCode, cbtotal: 0 });
    if (cbInsErr) {
      if (cbInsErr.code === "23505") {
        result.cashBack = true;
        logger.info(SCOPE, "tb_cash_back insert hit unique constraint — already seeded (no orphan)", {
          memberCode,
        });
      } else {
        logger.error(SCOPE, "tb_cash_back seed failed — new customer has no cashback row", cbInsErr, {
          memberCode,
          code: cbInsErr.code,
          message: cbInsErr.message,
        });
      }
    } else {
      result.cashBack = true;
      logger.info(SCOPE, "tb_cash_back row seeded for new signup", { memberCode });
    }
  }

  return result;
}

/**
 * Look up an existing legacy `tb_users` account by phone — used by the signup
 * guard (actions/auth.ts) to BLOCK a re-registration that would otherwise mint
 * a parallel orphan identity (profiles/corporate disconnected from the real
 * customer). Returns the existing `userID` (member code) or null.
 *
 * The customer's phone is the stable key: `tb_users.userTel` carries a UNIQUE
 * index. We convert the signup's E.164 phone to the legacy 10-digit form before
 * the lookup. Fail-open on a transient read error (return null = allow signup)
 * so a DB hiccup never blocks a legitimate new customer.
 */
export async function findLegacyUserIdByPhone(
  admin: SupabaseClient,
  phone: string,
): Promise<string | null> {
  const legacyTel = e164ToLegacyThaiPhone(phone);
  if (!legacyTel) return null;
  const { data, error } = await admin
    .from("tb_users")
    .select("userID, userStatus")
    .eq("userTel", legacyTel)
    .maybeSingle<{ userID: string; userStatus: string | null }>();
  if (error) {
    logger.warn(SCOPE, "phone-existence pre-check failed — allowing signup (fail-open)", {
      phone: redactPhone(phone),
      reason: error.message,
    });
    return null;
  }
  // userStatus='0' = legacy soft-deleted account. A deleted legacy account
  // should NOT block a fresh signup (the customer genuinely starts over).
  if (data && data.userStatus !== "0") return data.userID;
  return null;
}

/**
 * P1-16 (2026-05-30) — write the legacy `tb_corporate` row for a juristic
 * signup, keyed by `userid` = member_code. This is the faithful port of
 * `check-otp-register.php` L101-103:
 *
 *     INSERT INTO tb_corporate
 *       (userID, corporateNumber, corporateName, corporateAddress,
 *        corporateFile, corporateFile20, cpDateCreate, corporateStatus)
 *     VALUES ('$userID', '$corporateNumber', '$corporateName',
 *        '$corporateAddress', '$corporateFile', '$corporateFile20',
 *        NOW(), '1');
 *
 * BUG it fixes: Pacred's `saveJuristicStep2` upserted ONLY the REBUILT empty
 * `corporate` table (keyed by profile_id UUID, migration 0004) — a silent
 * dead-write. The legacy admin surfaces + tax-invoice eligibility read
 * `tb_corporate` (keyed by userid), so a native juristic customer's company
 * data was invisible to ops + never verifiable.
 *
 * Flow-order note: the legacy single-step register had all corporate fields
 * at once. Pacred's juristic signup is 3-step — step 1 creates auth+profile
 * (no corporate data yet), step 2 collects taxId/companyName/address, step 3
 * uploads the affidavit file. So this lands at STEP 2 (the moment the data
 * exists). The NOT-NULL file columns get `""` on insert (the affidavit is
 * uploaded in step 3) — legacy PHP wrote empty strings, never NULL
 * (docs/learnings/php-port-patterns.md). corporatestatus='1' = PENDING
 * (CORP_STATUS.PENDING · lib/admin/customer-identity.ts).
 *
 * Mirrors `adminConvertToJuristic` (actions/admin/customers.ts L728-754):
 * INSERT if no row, UPDATE if a row already exists (re-edit of step 2).
 * tb_corporate is all-lowercase (NOT in the 0113 camelCase batch).
 *
 * Best-effort: logs + returns `{ok:false}` on failure, never throws — the
 * caller has already committed the customer's auth + profile; losing the
 * tb_corporate mirror is bad but recoverable by ops, not a reason to error
 * the whole step-2 save.
 */
export async function upsertLegacyCorporate(
  admin: SupabaseClient,
  input: {
    /** member_code (`PR<n>`) — the legacy tb_corporate.userid key. */
    memberCode: string;
    /** 13-digit corporate/tax number → tb_corporate.corporatenumber. */
    corporateNumber: string;
    /** Company name → tb_corporate.corporatename. */
    corporateName: string;
    /** Full address string → tb_corporate.corporateaddress. */
    corporateAddress: string;
  },
): Promise<{ ok: boolean; error?: string }> {
  const { memberCode, corporateNumber, corporateName, corporateAddress } = input;
  if (!memberCode) {
    logger.error(SCOPE, "upsertLegacyCorporate: missing memberCode — skipping", undefined, {});
    return { ok: false, error: "missing_member_code" };
  }

  // INSERT vs UPDATE — does a tb_corporate row already exist for this member?
  const { data: existing, error: existErr } = await admin
    .from("tb_corporate")
    .select("id")
    .eq("userid", memberCode)
    .maybeSingle<{ id: number }>();
  if (existErr) {
    // Not fatal — the write below re-surfaces a real problem. Log + continue
    // as an INSERT (the more common case for a fresh signup).
    logger.warn(SCOPE, "tb_corporate existence pre-check failed — continuing as insert", {
      memberCode,
      reason: existErr.message,
    });
  }

  let writeErr;
  if (existing) {
    // Re-edit of step 2 — UPDATE the existing pending row (don't touch the
    // file columns; the affidavit is managed by step 3). Mirrors
    // adminConvertToJuristic's UPDATE branch.
    ({ error: writeErr } = await admin
      .from("tb_corporate")
      .update({
        corporatenumber: corporateNumber,
        corporatename: corporateName,
        corporateaddress: corporateAddress,
      })
      .eq("id", existing.id));
  } else {
    // Fresh signup — INSERT. corporatefile/corporatefile20 = "" (uploaded in
    // step 3), corporatestatus = "1" (PENDING), cpdatecreate rides its
    // DEFAULT CURRENT_TIMESTAMP (legacy NOW()).
    ({ error: writeErr } = await admin
      .from("tb_corporate")
      .insert({
        userid: memberCode,
        corporatenumber: corporateNumber,
        corporatename: corporateName,
        corporateaddress: corporateAddress,
        corporatefile: "",
        corporatefile20: "",
        corporatestatus: "1",
      }));
  }

  if (writeErr) {
    logger.error(SCOPE, "tb_corporate write failed — juristic company data not mirrored to legacy", writeErr, {
      memberCode,
      mode: existing ? "update" : "insert",
      code: writeErr.code,
      message: writeErr.message,
      details: writeErr.details,
    });
    return { ok: false, error: writeErr.message };
  }

  logger.info(SCOPE, "tb_corporate row written for juristic signup", {
    memberCode,
    mode: existing ? "update" : "insert",
  });
  return { ok: true };
}

/**
 * Strip the `+66` E.164 prefix and re-prepend `0` so the legacy
 * tb_users.usertel column gets the 10-digit local-thai form it expects.
 * Pass-through for non-`+66` inputs (defensive — legacy column accepts
 * up to varchar(13) so a +66/+1 string still fits if the format diverges).
 */
function e164ToLegacyThaiPhone(e164: string): string {
  const s = (e164 ?? "").trim();
  if (!s) return "";
  if (s.startsWith("+66")) {
    return "0" + s.slice(3);
  }
  return s.slice(0, 13);
}
