/**
 * Legacy `tb_users` bridge — write a tb_users row for a freshly-signed-up
 * Pacred customer so the admin /admin/customers/pending queue can see them.
 *
 * E2E loop fix · Agent F1 · 2026-05-29 (Gap #1):
 *   Before this helper, `registerPersonal` + `registerJuristicStep1` wrote
 *   ONLY to `profiles` with status='active' / 'incomplete'. The admin
 *   pending queue (`/admin/customers/pending`) reads `tb_users WHERE
 *   userActive='0'` — so new Pacred signups never appeared in the queue
 *   and were therefore never approved/auto-assigned to a sales rep. The
 *   approve action also flips `tb_users.userActive='1'`, so without a
 *   tb_users row the approve flow had nothing to act on.
 *
 *   This bridge closes that gap: after the profile insert succeeds and
 *   the trigger has minted a `member_code` (e.g. PR12345), call
 *   `insertLegacyTbUserRow()` to mirror the customer into `tb_users` with:
 *     - userID         = member_code
 *     - userActive     = '0'    (= pending approval; admin queue picks up)
 *     - userStatus     = '1'    (= active not-deleted)
 *     - userRegistered = now()
 *     - userName/userLastName/userTel/userEmail populated from form
 *     - userCompany    = '0' (personal) or '1' (juristic)
 *
 * Transaction safety
 *   The profile insert happens first; this bridge runs after. If the
 *   tb_users insert fails the profile row stays (the customer's auth +
 *   profile still work — just no pending-queue visibility). We log loud
 *   so ops can manually `INSERT INTO tb_users` and approve. We do NOT
 *   roll back the profile because that would also have to delete the
 *   auth.user — a 3-table rollback that's much riskier than the visible
 *   ops follow-up.
 *
 * Post-0113 schema: `tb_users` columns are camelCase + quoted (per
 * migration 0113). All select/insert keys use the quoted camelCase form.
 *
 * Server-only.
 */
import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { logger, redactPhone } from "@/lib/logger";

const SCOPE = "legacy-bridge-tb-users";

export type LegacyTbUserInput = {
  /** Generated by the profiles trigger — `PR<n>` form (e.g. `PR12345`). */
  memberCode: string;
  /** E.164 phone (already normalized by `normalizePhone()` in the action). */
  phone: string;
  /** Empty string OK — column is nullable in 0081 + later. */
  email: string | null;
  /** "personal" → userCompany='0' · "juristic" → userCompany='1'. */
  accountType: "personal" | "juristic";
  /** First name (personal) — empty string for juristic step 1 (filled in step 2). */
  firstName: string | null;
  /** Last name (personal) — empty string for juristic step 1. */
  lastName: string | null;
};

/**
 * Insert a tb_users row mirroring a freshly-created profile. Best-effort:
 * logs + returns `{ok:false}` on failure, never throws (the caller has
 * already committed the profile + auth user — losing the tb_users mirror
 * is bad but not catastrophic; ops can manually backfill).
 *
 * Idempotent on userID conflict — if a tb_users row with the same
 * member_code already exists (rare edge: rerun of /register with same
 * member_code already assigned), we no-op rather than fail.
 */
export async function insertLegacyTbUserRow(
  admin: SupabaseClient,
  input: LegacyTbUserInput,
): Promise<{ ok: boolean; error?: string }> {
  const {
    memberCode,
    phone,
    email,
    accountType,
    firstName,
    lastName,
  } = input;

  if (!memberCode) {
    logger.error(SCOPE, "missing memberCode — refusing to insert tb_users row", undefined, {});
    return { ok: false, error: "missing_member_code" };
  }

  // tb_users.usertel is varchar(13) NOT NULL and legacy stored 10-digit
  // local phone (`0948782006`). Pacred profiles store E.164 (`+66948782006`).
  // Strip the `+66` and re-prepend `0` so the legacy column gets the
  // 10-digit form the legacy ops UI expects.
  const legacyTel = e164ToLegacyThaiPhone(phone);

  // userRegistered is a `timestamp without time zone` per 0081 — use
  // ISO without timezone. Supabase REST handles the date+time string;
  // for fidelity with legacy NOW() we use UTC-now ISO.
  const nowIso = new Date().toISOString();

  // Pre-check — idempotent guard. The next attempt of /register with
  // the same identifier hits the profile-unique-constraint long before
  // here, but on the off chance a partial state landed (the only way
  // this happens is an admin manually restored a profile but its
  // tb_users row was deleted) we no-op rather than fail.
  const { data: existing, error: existingErr } = await admin
    .from("tb_users")
    .select("userID")
    .eq("userID", memberCode)
    .maybeSingle();
  if (existingErr) {
    // Not fatal — the insert below will re-surface the same error if
    // it's a real problem (RLS / column / schema). Log + continue.
    logger.warn(SCOPE, "tb_users existence pre-check failed — continuing to insert", {
      memberCode,
      reason: existingErr.message,
    });
  }
  if (existing) {
    logger.info(SCOPE, "tb_users row already exists — skipping insert (idempotent)", {
      memberCode,
    });
    return { ok: true };
  }

  // Phone-collision guard. `tb_users.userTel` carries a UNIQUE index
  // (`idx_*_usertel`) — a raw insert with a phone that already belongs to
  // another userID throws 23505 and (pre-2026-05-29) silently orphaned the
  // signup. This happens for genuine re-registrations (same person signs up
  // again with a fresh member_code) + legacy rows that share the number.
  // We pre-check and no-op: the customer already HAS a tb_users identity
  // under the other code, so the admin queue + approve flow can still act on
  // them via that row. Logged at info (expected), not error.
  const { data: phoneOwner } = await admin
    .from("tb_users")
    .select("userID")
    .eq("userTel", legacyTel)
    .maybeSingle();
  if (phoneOwner) {
    logger.info(
      SCOPE,
      "tb_users phone already registered under another member — skipping insert (no orphan)",
      { memberCode, existingUserID: phoneOwner.userID, phone: redactPhone(phone) },
    );
    return { ok: true };
  }

  // Pacred-native customers default useractive='0' (= pending admin
  // approval). The admin queue at /admin/customers/pending reads
  // `userActive='0'` to enumerate this list. Approval (Sub-fix B) flips
  // to '1' and triggers the SMS + sales-rep auto-assign.
  //
  // NOT-NULL columns per 0081 (carry sane defaults so the insert
  // doesn't trip a constraint violation):
  //   userLineNotify · userCompany · userComparison · userComparisonValue
  //   userCredit · userCreditValue · userCreditDate · shopUser · channel
  //   userRecom · userAddressID · userTransportType · userShipBy
  //   userPayMethod · userNote · userLineIDOA · companyCustomer
  //   userPicture · userPass · coID
  //
  // userPass is varchar(80) NOT NULL — supabase auth holds the real password.
  // Empty string here is intentional: legacy admin UIs read userPass only when
  // the user signs in via the legacy /member/login.php flow, which Pacred users
  // never use (they go through Supabase auth on /login). The bridge sign-in
  // (`pcs-legacy-bridge.ts`) operates the OTHER direction — legacy → Supabase.
  const payload: Record<string, unknown> = {
    userID:               memberCode,
    userTel:              legacyTel,
    userStatus:           "1",   // 1=ใช้งาน (not deleted)
    userActive:           "0",   // 0=pending admin approval
    userPass:             "",    // not used by Pacred-native auth path
    userName:             firstName ?? "",
    userLastName:         lastName  ?? "",
    userEmail:            email ?? null,
    userRegistered:       nowIso,
    userPicture:          "user.jpg",
    coID:                 "PR",  // Pacred co-id (legacy was 'PCS')
    userLineNotify:       "",
    userCompany:          accountType === "juristic" ? "1" : "0",
    userComparison:       "0",
    userComparisonValue:  0,
    userCredit:           "0",
    userCreditValue:      0,
    userCreditDate:       0,
    shopUser:             "1",   // ซื้อไปใช้เอง default
    channel:              "",
    userRecom:            "",
    userAddressID:        "",
    userTransportType:    "",
    userShipBy:           "",
    userPayMethod:        "",
    userNote:             "",
    userLineIDOA:         "",
    companyCustomer:      "0",
  };

  const { error: insertErr } = await admin.from("tb_users").insert(payload);
  if (insertErr) {
    // 23505 = unique_violation. A phone-collision that slipped past the
    // pre-check above (race between two concurrent signups, or the legacy
    // usertel index) is NOT an orphan risk worth an error page — the other
    // row already represents this customer's identity. Degrade to info.
    if (insertErr.code === "23505") {
      logger.info(SCOPE, "tb_users insert hit unique constraint — treating as already-present (no orphan)", {
        memberCode,
        constraint: insertErr.details ?? insertErr.message,
      });
      return { ok: true };
    }
    logger.error(SCOPE, "tb_users insert failed — orphan profile risk", insertErr, {
      memberCode,
      accountType,
      phone: redactPhone(phone),
      code: insertErr.code,
      message: insertErr.message,
      details: insertErr.details,
      hint:    insertErr.hint,
    });
    return { ok: false, error: insertErr.message };
  }

  logger.info(SCOPE, "tb_users row created for new signup", {
    memberCode,
    accountType,
  });
  return { ok: true };
}

/**
 * Strip the `+66` E.164 prefix and re-prepend `0` so the legacy
 * tb_users.usertel column gets the 10-digit local-thai form it expects.
 * Pass-through for non-`+66` inputs (defensive — legacy column accepts
 * up to varchar(13) so a +66/+1 string still fits if the format diverges).
 */
function e164ToLegacyThaiPhone(e164: string): string {
  const s = (e164 ?? "").trim();
  if (!s) return "";
  if (s.startsWith("+66")) {
    return "0" + s.slice(3);
  }
  return s.slice(0, 13);
}
