/**
 * Integration test for the auth signup flow (P-30 — Sprint 7+ Track A).
 *
 * Hits real Supabase (admin client, bypasses RLS) and exercises the
 * cross-table chain that registerPersonal / registerJuristicStep1+2 in
 * actions/auth.ts go through:
 *
 *   1. Personal signup happy path:
 *      auth user → profile (account_type='personal', status='incomplete')
 *      → member_code auto-generated by trigger (PR<5-digit-seq>)
 *      → mimic complete-profile: status='incomplete' → 'active'
 *
 *   2. Juristic signup happy path:
 *      auth user → profile (account_type='juristic', status='incomplete')
 *      → corporate row insert (tax_id + company_name + status='pending')
 *      → member_code still generated regardless of account_type
 *      → second profile member_code != first (sequence advances)
 *
 *   3. member_code format invariant: matches /^PR\d{5}$/ for both rows
 *
 * DECISION (per §6 self-directed):
 * - Same approach as P-26 / P-28 / P-29: drive DB via admin client, do
 *   not import server actions (they call createClient() which depends on
 *   Next.js cookies()). The trigger + schema constraints are what we
 *   actually want to test — the action wrappers add Zod validation +
 *   user lookup but the persistence guarantees live in the DB.
 *
 * Run with:  pnpm tsx --env-file=.env.local lib/auth/signup.test.ts
 * Or:        pnpm test  (chained)
 *
 * Skips gracefully (exit 0) if SUPABASE env vars are missing.
 */

import { createClient } from "@supabase/supabase-js";

let pass = 0;
let fail = 0;

function assertEq(label: string, actual: unknown, expected: unknown) {
  if (JSON.stringify(actual) === JSON.stringify(expected)) {
    pass++;
    console.log(`  ✓ ${label}`);
  } else {
    fail++;
    console.error(`  ✗ ${label}\n    expected: ${JSON.stringify(expected)}\n    actual:   ${JSON.stringify(actual)}`);
  }
}

function assertTrue(label: string, condition: boolean, hint?: string) {
  if (condition) {
    pass++;
    console.log(`  ✓ ${label}`);
  } else {
    fail++;
    console.error(`  ✗ ${label}${hint ? `\n    ${hint}` : ""}`);
  }
}

function assertMatch(label: string, value: string | null | undefined, re: RegExp) {
  if (typeof value === "string" && re.test(value)) {
    pass++;
    console.log(`  ✓ ${label}`);
  } else {
    fail++;
    console.error(`  ✗ ${label}\n    expected to match: ${re}\n    actual:            ${JSON.stringify(value)}`);
  }
}

console.log("=== auth signup integration test (P-30) ===");

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    console.log("⏭  SUPABASE env vars unset — skipping integration test (this is OK for CI without secrets).");
    process.exit(0);
  }

  const admin = createClient(url, key, { auth: { persistSession: false } });

  // Per-run unique tag so concurrent tests don't collide on phone uniqueness
  const runId         = Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
  const phonePersonal = `09${(Date.now() % 10_000_000).toString().padStart(7, "0")}`;
  // Ensure juristic phone differs from personal even when Date.now() collides
  const phoneJuristic = `08${(Date.now() % 10_000_000).toString().padStart(7, "0")}`;

  let personalUserId:  string | null = null;
  let juristicUserId:  string | null = null;

  async function cleanup() {
    console.log("\n🧹 cleanup");
    try {
      // corporate rows cascade from profiles FK; profiles cascade from auth.users
      // Belt + suspenders.
      if (juristicUserId) {
        await admin.from("corporate").delete().eq("profile_id", juristicUserId);
        await admin.from("profiles").delete().eq("id", juristicUserId);
        await admin.auth.admin.deleteUser(juristicUserId);
      }
      if (personalUserId) {
        await admin.from("profiles").delete().eq("id", personalUserId);
        await admin.auth.admin.deleteUser(personalUserId);
      }
      console.log("  ✓ cleanup done");
    } catch (e) {
      console.error("  ✗ cleanup error (non-fatal):", e instanceof Error ? e.message : e);
    }
  }

  try {
    // ────────────────────────────────────────────────────────
    // 1. Personal signup
    // ────────────────────────────────────────────────────────
    console.log("\n1. personal signup happy path");

    const { data: pAuth, error: pAuthErr } = await admin.auth.admin.createUser({
      email: `p30-personal-${runId}@pacred-test.local`,
      password: "Test123!secure",
      email_confirm: true,
    });
    assertEq("personal auth user created", pAuthErr?.message ?? null, null);
    personalUserId = pAuth.user?.id ?? null;
    if (!personalUserId) throw new Error("personal auth user creation returned no id");

    const { error: pProfErr } = await admin.from("profiles").insert({
      id:           personalUserId,
      first_name:   "P30Personal",
      last_name:    "Test",
      phone:        phonePersonal,
      account_type: "personal",
      status:       "incomplete",
    });
    assertEq("personal profile insert ok", pProfErr?.message ?? null, null);

    const { data: pProfile } = await admin
      .from("profiles")
      .select("member_code, status, account_type")
      .eq("id", personalUserId)
      .maybeSingle<{ member_code: string | null; status: string; account_type: string }>();

    assertTrue("personal profile readback non-null", pProfile != null);
    assertMatch("personal member_code matches /^PR\\d{5}$/", pProfile?.member_code, /^PR\d{5}$/);
    assertEq("personal initial status = incomplete", pProfile?.status, "incomplete");
    assertEq("account_type = personal", pProfile?.account_type, "personal");

    // Mimic complete-profile flow: flip status → active
    await admin
      .from("profiles")
      .update({ status: "active" })
      .eq("id", personalUserId);
    const { data: pAfterComplete } = await admin
      .from("profiles")
      .select("status")
      .eq("id", personalUserId)
      .maybeSingle<{ status: string }>();
    assertEq("personal status flips to active after complete-profile", pAfterComplete?.status, "active");

    // ────────────────────────────────────────────────────────
    // 2. Juristic signup happy path
    // ────────────────────────────────────────────────────────
    console.log("\n2. juristic signup happy path");

    const { data: jAuth, error: jAuthErr } = await admin.auth.admin.createUser({
      email: `p30-juristic-${runId}@pacred-test.local`,
      password: "Test123!secure",
      email_confirm: true,
    });
    assertEq("juristic auth user created", jAuthErr?.message ?? null, null);
    juristicUserId = jAuth.user?.id ?? null;
    if (!juristicUserId) throw new Error("juristic auth user creation returned no id");

    const { error: jProfErr } = await admin.from("profiles").insert({
      id:           juristicUserId,
      first_name:   "P30Juristic",
      last_name:    "Test",
      phone:        phoneJuristic,
      account_type: "juristic",
      status:       "incomplete",
    });
    assertEq("juristic profile insert ok", jProfErr?.message ?? null, null);

    const { error: corpErr } = await admin.from("corporate").insert({
      profile_id:      juristicUserId,
      tax_id:          "0105560123459",  // 13-digit tax id (synthetic — fails real DBD)
      company_name:    `Pacred Test Co (${runId})`,
      company_address: "1 Test Road, Bangkok 10110",
    });
    assertEq("corporate row insert ok", corpErr?.message ?? null, null);

    const { data: jProfile } = await admin
      .from("profiles")
      .select("member_code, account_type")
      .eq("id", juristicUserId)
      .maybeSingle<{ member_code: string | null; account_type: string }>();
    assertMatch("juristic member_code also matches /^PR\\d{5}$/", jProfile?.member_code, /^PR\d{5}$/);
    assertEq("juristic account_type = juristic", jProfile?.account_type, "juristic");

    // Sequence advances — juristic code numerically > personal code
    if (pProfile?.member_code && jProfile?.member_code) {
      const pNum = Number(pProfile.member_code.slice(2));
      const jNum = Number(jProfile.member_code.slice(2));
      assertTrue(
        `juristic member_code seq > personal (P=${pProfile.member_code}, J=${jProfile.member_code})`,
        jNum > pNum,
      );
    }

    // Corporate row reachable + has expected default status
    const { data: corp } = await admin
      .from("corporate")
      .select("tax_id, company_name, status")
      .eq("profile_id", juristicUserId)
      .maybeSingle<{ tax_id: string; company_name: string; status: string }>();
    assertEq("corporate.tax_id roundtrip", corp?.tax_id, "0105560123459");
    assertEq("corporate.status default = pending", corp?.status, "pending");
  } finally {
    await cleanup();
  }

  console.log(`\n${pass} pass, ${fail} fail`);
  if (fail > 0) process.exit(1);
}

main().catch((e) => {
  console.error("FATAL:", e);
  process.exit(1);
});
